import { Platform, StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#1344FF',
  background: '#FFFFFF',
  card: '#FFFFFF',
  text: '#111827',
  textSecondary: '#6B7280',
  placeholder: '#9CA3AF',
  border: '#E5E7EB',
  borderLight: '#F3F4F6',
  white: '#FFFFFF',
  surface: '#F9FAFB',
};

export const FONTS = {
  regular: 'Pretendard-Regular',
  medium: 'Pretendard-Medium',
  semibold: 'Pretendard-SemiBold',
  bold: 'Pretendard-Bold',
};

export const HOUR_HEIGHT = 180;
export const MINUTE_HEIGHT = HOUR_HEIGHT / 60;
export const MIN_ITEM_HEIGHT = 45;
export const GRID_SNAP_HEIGHT = HOUR_HEIGHT / 4;

export const GRID_TOP_OFFSET = 40;
export const BOTTOM_TAB_BAR_HEIGHT = Platform.OS === 'ios' ? 85 : 60;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingTop: 0,
  },
  topBarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  topBarBackButton: {
    padding: 4,
  },
  topBarHeaderTitle: {
    fontSize: 18,
    fontFamily: FONTS.bold,
    fontWeight: 'bold',
    color: '#111827',
  },
  topToolbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
    marginTop: 0,
    paddingTop: 4,
    paddingBottom: 6,
    backgroundColor: COLORS.background,
  },
  toolbarLeftGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
    gap: 6,
  },
  toolbarRightGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  toolbarTitleButton: {
    maxWidth: 120,
    minHeight: 30,
    justifyContent: 'center',
  },
  toolbarTitleText: {
    fontSize: 16,
    fontFamily: FONTS.bold,
    color: COLORS.text,
    lineHeight: 20,
  },
  toolbarTitleInput: {
    minWidth: 120,
    maxWidth: 170,
    minHeight: 28,
    paddingVertical: 0,
    paddingHorizontal: 0,
    fontSize: 16,
    fontFamily: FONTS.bold,
    color: COLORS.text,
    lineHeight: 20,
  },
  toolbarIconButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  toolbarIconButtonPlain: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  toolbarIconButtonInfo: {
    backgroundColor: '#E5E7EB',
    borderColor: '#E5E7EB',
  },
  toolbarIconButtonOutlineBlue: {
    backgroundColor: '#FFFFFF',
    borderColor: COLORS.primary,
    borderWidth: 1.5,
  },
  toolbarIconButtonOutlineDark: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D1D5DB',
    borderWidth: 1.5,
  },
  toolbarIconButtonFilledGray: {
    backgroundColor: '#E5E7EB',
    borderColor: '#E5E7EB',
  },
  toolbarIconButtonFilledBlue: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  toolbarIconButtonActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  toolbarIconButtonDisabled: {
    opacity: 0.55,
  },
  toolbarBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#FF3B30',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 3,
    borderWidth: 2,
    borderColor: COLORS.background,
  },
  toolbarBadgeText: {
    color: COLORS.white,
    fontSize: 9,
    fontFamily: FONTS.bold,
    lineHeight: 12,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 17,
    fontFamily: FONTS.semibold,
    color: COLORS.text,
  },
  headerInput: {
    fontSize: 17,
    fontFamily: FONTS.semibold,
    color: COLORS.text,
    borderBottomWidth: 1,
    borderColor: COLORS.placeholder,
    padding: 0,
    minWidth: 150,
  },
  headerDoneButton: {
    marginRight: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
  },
  headerDoneButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontFamily: FONTS.semibold,
  },
  dayTabsWrapper: {
    backgroundColor: COLORS.card,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 0,
    paddingRight: 12,
    paddingTop: 10,
    paddingBottom: 8,
    gap: 8,
  },
  dayTabsContainer: {
    alignItems: 'center',
    paddingVertical: 0,
    paddingLeft: 16,
    paddingRight: 16,
    gap: 8,
  },
  dayTabsScroll: {
    flex: 1,
  },
  dayTab: {
    minWidth: 80,
    minHeight: 36,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 10,
    marginRight: 8,
    backgroundColor: COLORS.card,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 6,
  },
  dayTabSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  dayTabUnselected: {
    backgroundColor: '#FFFFFF',
  },
  dayTabLabel: {
    textAlign: 'center',
    fontSize: 13,
    color: COLORS.text,
    fontFamily: FONTS.semibold,
    lineHeight: 15,
  },
  dayTabLabelSelected: {
    color: COLORS.white,
  },
  dayTabDayNumber: {
    fontSize: 14,
    fontFamily: FONTS.bold,
    color: COLORS.text,
    lineHeight: 16,
  },
  dayTabDayNumberSelected: {
    color: COLORS.white,
  },
  dayTabDateInline: {
    fontSize: 11,
    fontFamily: FONTS.regular,
    color: COLORS.placeholder,
    lineHeight: 14,
  },
  dayTabDateInlineSelected: {
    color: COLORS.white,
    opacity: 0.85,
  },
  dayEditButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 2,
  },
  bottomTabBar: {
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 20,
    elevation: 0,
    height: Platform.OS === 'ios' ? 85 : 60,
    paddingTop: 8,
    paddingBottom: Platform.OS === 'ios' ? 28 : 8,
  },
  bottomTabContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 8,
  },
  bottomTabItem: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomTabIcon: {
    marginBottom: 0,
    minHeight: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomTabLabel: {
    fontFamily: FONTS.semibold,
    fontSize: 11,
    marginTop: -2,
    lineHeight: 14,
    color: COLORS.placeholder,
  },
  bottomTabLabelActive: {
    color: COLORS.primary,
  },
  tabScene: {
    flex: 1,
    paddingBottom: BOTTOM_TAB_BAR_HEIGHT,
  },
  tabContentContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  timelineStage: {
    flex: 1,
    position: 'relative',
  },
  timelineSceneBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: COLORS.surface,
  },
  timelineWeatherOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    elevation: 20,
  },
  timelineContentContainer: {
    paddingBottom: 0,
    backgroundColor: 'transparent',
  },
  timelineWrapper: {
    position: 'relative',
    paddingVertical: 20,
  },
  gridContainer: {
    paddingVertical: 20,
  },
  hourBlock: {
    flexDirection: 'row',
  },
  hourLabelContainer: {
    width: 60,
    height: HOUR_HEIGHT,
    position: 'relative',
    alignItems: 'center',
  },
  timeLabelText: {
    position: 'absolute',
    marginTop: -8,
    color: COLORS.placeholder,
    fontSize: 12,
    fontFamily: FONTS.medium,
    width: '100%',
    textAlign: 'center',
  },
  minuteLabel: {},
  hourContent: {
    flex: 1,
    marginLeft: 0,
    height: HOUR_HEIGHT,
    flexDirection: 'column',
    position: 'absolute',
    left: 60,
    right: 15,
  },
  quarterBlock: {
    height: HOUR_HEIGHT / 4,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB', 
  },
  firstQuarterBlock: {
    borderTopColor: '#9CA3AF', 
  },
  addPlaceListContainer: {
    flex: 1,
  },
  searchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: COLORS.card,
  },
  searchInput: {
    flex: 1,
    height: 40,
    backgroundColor: COLORS.surface,
    borderRadius: 8,
    paddingHorizontal: 15,
    marginRight: 10,
    fontFamily: FONTS.regular,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  searchButton: {
    padding: 10,
  },
  searchButtonIcon: {
    fontSize: 20,
  },
  placeTypeTabContainer: {
    flexDirection: 'row',
    paddingHorizontal: 15,
    paddingTop: 10,
    paddingBottom: 5,
    backgroundColor: COLORS.card,
  },
  placeTypeTab: {
    marginRight: 15,
    paddingVertical: 10,
  },
  placeTypeTabSelected: {
    borderBottomWidth: 2,
    borderBottomColor: COLORS.primary,
  },
  placeTypeTabText: {
    fontSize: 16,
    color: COLORS.placeholder,
    fontFamily: FONTS.semibold,
  },
  placeTypeTabTextSelected: {
    color: COLORS.primary,
  },
  resultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.card,
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  resultImage: {
    width: 40,
    height: 40,
    borderRadius: 8,
  },
  placeholderImage: {
    backgroundColor: COLORS.surface,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  placeholderText: {
    fontSize: 16,
    fontFamily: FONTS.bold,
    color: COLORS.placeholder,
  },
  resultName: {
    fontSize: 16,
    fontFamily: FONTS.semibold,
    color: COLORS.text,
  },
  resultMeta: {
    fontSize: 12,
    fontFamily: FONTS.regular,
    color: COLORS.placeholder,
    marginTop: 2,
  },
  resultAddress: {
    fontSize: 12,
    fontFamily: FONTS.regular,
    color: COLORS.placeholder,
    marginTop: 2,
  },

  resizeHandleTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 32,
    zIndex: 10,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 5,
  },
  resizeHandleBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 32,
    zIndex: 10,
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 5,
  },
  resizeHandleIndicator: {
    width: 44,
    height: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(156, 163, 175, 0.24)',
    borderWidth: 1,
    borderColor: 'rgba(156, 163, 175, 0.7)',
  },
  emptyContainer: {
    padding: 20,
    alignItems: 'center',
  },
  emptyText: {
    color: COLORS.placeholder,
    fontFamily: FONTS.regular,
  },
  resultInfo: {
    flex: 1,
    marginLeft: 10,
  },
  timeLabelTop: {
    top: 0,
  },
  flex1: {
    flex: 1,
  },
  marginTop20: {
    marginTop: 20,
  },

  onlineUsersContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  onlineUsersWrapper: {
    flexDirection: 'row',
    marginRight: 10,
  },
  onlineUserAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.primary,
    borderWidth: 2,
    borderColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  moreUsersAvatar: {
    backgroundColor: COLORS.placeholder,
  },
  onlineUserInitials: {
    color: 'white',
    fontSize: 13,
    fontFamily: FONTS.bold,
  },
  moreUsersText: {
    color: 'white',
    fontSize: 11,
    fontFamily: FONTS.medium,
  },

  overflowBanner: {
    position: 'absolute',
    bottom: 16,
    left: 20,
    right: 20,
    backgroundColor: '#1F2937',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  overflowBannerText: {
    color: COLORS.white,
    fontSize: 13,
    fontFamily: FONTS.semibold,
  },

  floatingHistoryContainer: {
    position: 'absolute',
    bottom: BOTTOM_TAB_BAR_HEIGHT + 16,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
    zIndex: 30,
  },
  floatingHistoryButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2.5,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  floatingHistoryButtonDisabled: {
    backgroundColor: '#F3F4F6',
    opacity: 0.5,
  },
});
