import { StyleSheet } from 'react-native';
import { tokens } from '../../../theme/tokens';
import { normalize } from '../../../utils/normalize';

export const COLORS = {
  primary: tokens.colors.primary,
  primaryTint: tokens.colors.primaryTint,
  background: tokens.colors.background,
  card: tokens.colors.white,
  text: tokens.colors.text,
  textSecondary: tokens.colors.textSecondary,
  placeholder: tokens.colors.textTertiary,
  border: tokens.colors.border,
  borderLight: tokens.colors.borderLight,
  white: tokens.colors.white,
  surface: tokens.colors.surface,
  danger: tokens.tones.danger.fg,
};

export const FONTS = tokens.fontFamily;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingTop: 0,
  },
  topBarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: normalize(16),
    height: normalize(56),
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  topBarBackButton: {
    padding: normalize(4),
  },
  topBarHeaderTitle: {
    fontSize: normalize(18),
    fontFamily: FONTS.bold,
    fontWeight: 'bold',
    color: COLORS.text,
  },
  topBarSpacer: {
    width: normalize(28),
  },
  topToolbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: normalize(12),
    marginTop: 0,
    paddingTop: normalize(4),
    paddingBottom: normalize(6),
    backgroundColor: COLORS.background,
  },
  toolbarLeftGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
    gap: normalize(6),
  },
  toolbarRightGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  toolbarTitleButton: {
    maxWidth: normalize(120),
    minHeight: normalize(30),
    justifyContent: 'center',
  },
  toolbarTitleText: {
    fontSize: normalize(16),
    fontFamily: FONTS.bold,
    color: COLORS.text,
    lineHeight: normalize(20),
  },
  toolbarIconButton: {
    width: normalize(32),
    height: normalize(32),
    borderRadius: normalize(16),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  toolbarIconButtonPlain: {
    width: normalize(24),
    height: normalize(24),
    borderRadius: normalize(12),
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  toolbarIconButtonInfo: {
    backgroundColor: COLORS.border,
    borderColor: COLORS.border,
  },
  toolbarIconButtonOutlineBlue: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.primary,
    borderWidth: 1.5,
  },
  toolbarIconButtonOutlineDark: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.placeholder,
    borderWidth: 1.5,
  },
  toolbarIconButtonFilledGray: {
    backgroundColor: COLORS.border,
    borderColor: COLORS.border,
  },
  toolbarIconButtonFilledBlue: {
    width: 'auto',
    minWidth: normalize(44),
    height: 'auto',
    minHeight: normalize(32),
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  toolbarIconButtonActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  toolbarActionText: {
    color: COLORS.white,
    fontSize: normalize(13),
    fontFamily: FONTS.bold,
  },
  toolbarIconButtonDisabled: {
    opacity: 0.55,
  },
  toolbarBadge: {
    position: 'absolute',
    top: normalize(-4),
    right: normalize(-4),
    minWidth: normalize(16),
    height: normalize(16),
    borderRadius: normalize(8),
    backgroundColor: COLORS.danger,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: normalize(3),
    borderWidth: 2,
    borderColor: COLORS.background,
  },
  toolbarBadgeText: {
    color: COLORS.white,
    fontSize: normalize(9),
    fontFamily: FONTS.bold,
    lineHeight: normalize(12),
  },
  mapContainer: {
    height: '40%',
    paddingHorizontal: normalize(16),
    paddingTop: normalize(8),
    paddingBottom: normalize(4),
    backgroundColor: COLORS.background,
  },
  mapInner: {
    flex: 1,
    borderRadius: normalize(12),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  dayTabsWrapper: {
    position: 'relative',
    backgroundColor: COLORS.card,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: normalize(10),
    paddingBottom: normalize(8),
    gap: normalize(8),
  },
  dayTabsContainer: {
    alignItems: 'center',
    paddingVertical: 0,
    paddingLeft: normalize(16),
    paddingRight: normalize(16),
    gap: normalize(8),
  },
  dayTabsScroll: {
    flex: 1,
  },
  mapToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(4),
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(7),
    backgroundColor: COLORS.primaryTint,
    borderRadius: normalize(20),
    marginLeft: normalize(5),
  },
  mapToggleButtonActive: {
    backgroundColor: COLORS.primary,
  },
  mapToggleButtonText: {
    fontSize: normalize(12),
    fontFamily: FONTS.semibold,
    color: COLORS.primary,
  },
  mapToggleButtonTextActive: {
    color: COLORS.white,
  },
  dayTab: {
    minWidth: normalize(80),
    minHeight: normalize(36),
    paddingVertical: normalize(6),
    paddingHorizontal: normalize(14),
    borderRadius: normalize(10),
    marginRight: normalize(8),
    backgroundColor: COLORS.card,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: normalize(6),
  },
  dayTabSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  dayTabUnselected: {
    backgroundColor: COLORS.white,
  },
  dayTabLabel: {
    textAlign: 'center',
    fontSize: normalize(13),
    color: COLORS.text,
    fontFamily: FONTS.semibold,
    lineHeight: normalize(15),
  },
  dayTabLabelSelected: {
    color: COLORS.white,
  },
  dayTabDayNumber: {
    fontSize: normalize(14),
    fontFamily: FONTS.bold,
    color: COLORS.text,
    lineHeight: normalize(16),
  },
  dayTabDayNumberSelected: {
    color: COLORS.white,
  },
  dayTabDateInline: {
    fontSize: normalize(11),
    fontFamily: FONTS.regular,
    color: COLORS.placeholder,
    lineHeight: normalize(14),
  },
  dayTabDateInlineSelected: {
    color: COLORS.white,
    opacity: 0.85,
  },
  timelineStage: {
    flex: 1,
    position: 'relative',
    backgroundColor: COLORS.white,
  },
  timelineSceneBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: COLORS.white,
    zIndex: 0,
  },
  timelineWeatherOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    elevation: 20,
  },
  timelineContentContainer: {
    paddingBottom: 0,
    backgroundColor: 'transparent',
  },
  timelineWeatherPadding: {
    paddingTop: normalize(62),
  },
  footer: {
    flexDirection: 'row',
    padding: normalize(20),
    backgroundColor: COLORS.card,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  footerButton: {
    flex: 1,
    height: normalize(50),
    borderRadius: normalize(12),
    flexDirection: 'row',
    gap: normalize(6),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    marginHorizontal: normalize(5),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  footerButtonText: {
    fontSize: normalize(16),
    fontFamily: FONTS.bold,
    color: COLORS.text,
  },
  confirmButton: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  confirmButtonText: {
    color: COLORS.white,
    fontFamily: FONTS.bold,
  },
  flex1: {
    flex: 1,
  },
  dayTabsFadeOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: normalize(24),
    zIndex: 10,
  },
  dayTabsFadeOverlayLeft: {
    left: 0,
  },
  dayTabsFadeOverlayRight: {
    right: 0,
  },
  loadErrorContainer: {
    flex: 1,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: normalize(32),
    gap: normalize(16),
  },
  loadErrorText: {
    fontSize: normalize(14),
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
  loadErrorRetryButton: {
    paddingHorizontal: normalize(20),
    paddingVertical: normalize(10),
    borderRadius: normalize(10),
    backgroundColor: COLORS.primary,
  },
  loadErrorRetryText: {
    fontSize: normalize(14),
    fontFamily: FONTS.bold,
    color: COLORS.white,
  },
});
