org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
reactNativeArchitectures=arm64-v8a,x86_64
newArchEnabled=true
hermesEnabled=true
edgeToEdgeEnabled=false

PLANMATE_RELEASE_STORE_FILE=planmate-upload-key.keystore
PLANMATE_RELEASE_KEY_ALIAS=planmate-key
PLANMATE_RELEASE_STORE_PASSWORD=planmate1234
PLANMATE_RELEASE_KEY_PASSWORD=planmate1234
