import { StyleSheet } from 'react-native';
import { tokens } from '../../../../theme/tokens';
import { normalize } from '../../../../utils/normalize';

export const COLORS = tokens.colors;
export const DANGER = tokens.tones.danger.fg;

export const styles = StyleSheet.create({
  overlay: { flex: 1 },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(20, 27, 40, 0.36)',
  },
  popupLayer: { flex: 1 },
  popupRoot: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: normalize(20),
  },
  // maxHeight: '100%'는 부모의 패딩까지 포함한 높이를 기준으로 풀려서, 카드가
  // 안전 영역 여백 밖으로 넘쳐 위가 잘렸다. flexShrink는 패딩을 뺀 자리에
  // 맞춰 줄어드므로 상태바를 침범하지 않는다.
  popup: {
    width: '100%',
    maxWidth: normalize(420),
    height: normalize(560),
    flexShrink: 1,
    borderRadius: normalize(24),
    padding: normalize(18),
    backgroundColor: COLORS.white,
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingTop: normalize(4),
    paddingBottom: normalize(18),
    marginBottom: normalize(18),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  heading: { flex: 1 },
  eyebrow: {
    fontSize: normalize(10),
    fontFamily: tokens.fontFamily.bold,
    letterSpacing: 1.3,
    color: COLORS.primary,
    marginBottom: normalize(6),
  },
  title: {
    fontSize: normalize(23),
    fontFamily: tokens.fontFamily.bold,
    letterSpacing: -0.7,
    color: COLORS.text,
  },
  closeButton: {
    width: normalize(44),
    height: normalize(44),
    marginTop: normalize(-7),
    marginRight: normalize(-9),
    alignItems: 'center',
    justifyContent: 'center',
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
    paddingTop: normalize(16),
    marginTop: normalize(14),
  },
  tabRow: {
    flexDirection: 'row',
    padding: normalize(5),
    gap: normalize(4),
    borderRadius: normalize(14),
    backgroundColor: COLORS.borderLight,
  },
  // flexWrap이 걸리면 줄 자체의 세로 위치는 alignItems가 아니라 alignContent가
  // 정하고, 기본값 flex-start가 라벨을 알약 위쪽에 붙여 버린다.
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    minHeight: normalize(45),
    paddingVertical: normalize(8),
    borderRadius: normalize(10),
  },
  tabButtonActive: { backgroundColor: COLORS.white },
  tabLabel: {
    fontSize: normalize(13),
    fontFamily: tokens.fontFamily.semibold,
    color: COLORS.textSecondary,
  },
  tabLabelActive: { color: COLORS.primary },
  tabCount: {
    fontSize: normalize(11),
    fontFamily: tokens.fontFamily.regular,
    marginLeft: normalize(5),
    color: COLORS.textSecondary,
  },
  scopeHint: {
    paddingHorizontal: normalize(2),
    paddingTop: normalize(15),
    paddingBottom: normalize(13),
    fontSize: normalize(11),
    lineHeight: normalize(18),
    fontFamily: tokens.fontFamily.regular,
    color: COLORS.textSecondary,
  },
  listScroll: { flex: 1 },
  list: { paddingBottom: normalize(2) },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: normalize(52),
    paddingVertical: normalize(4),
    paddingLeft: normalize(2),
    backgroundColor: COLORS.white,
    paddingRight: normalize(4),
    marginBottom: normalize(6),
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: normalize(12),
  },
  // 웹은 끌고 있는 줄을 파란 면(#EFF6FF)과 반투명 파란 테두리로 알린다.
  // 안드로이드는 elevation만 읽으므로 짙은 그림자 대신 sm 한 단계만 얹는다.
  itemRowActive: {
    ...tokens.shadows.sm,
    backgroundColor: COLORS.primarySurface,
    borderColor: 'rgba(19, 68, 255, 0.3)',
  },
  itemToggle: {
    flex: 1,
    minHeight: normalize(44),
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    width: normalize(20),
    height: normalize(20),
    borderWidth: 2,
    borderRadius: normalize(6),
    borderColor: COLORS.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  itemText: {
    flex: 1,
    marginLeft: normalize(11),
    fontSize: normalize(14),
    lineHeight: normalize(21),
    fontFamily: tokens.fontFamily.regular,
    color: COLORS.text,
  },
  itemTextChecked: {
    color: COLORS.textSecondary,
    textDecorationLine: 'line-through',
  },
  itemAction: {
    width: normalize(44),
    height: normalize(44),
    alignItems: 'center',
    justifyContent: 'center',
  },
  dragHandle: {
    width: normalize(32),
    minHeight: normalize(48),
    alignItems: 'center',
    justifyContent: 'center',
  },
  // 바깥 껍데기는 쌓임 순서만 맡는다. itemRow의 marginBottom이 이 껍데기 높이에
  // 들어가서, 여기에 배경을 주면 파란 면이 카드보다 6px 아래로 삐져나온다.
  draggedItem: { zIndex: 2 },
  itemEditInput: {
    flex: 1,
    minHeight: normalize(44),
    paddingVertical: normalize(4),
    fontSize: normalize(14),
    fontFamily: tokens.fontFamily.regular,
    color: COLORS.text,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.primary,
  },
  stateBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: normalize(12),
  },
  emptyTitle: {
    fontSize: normalize(14),
    lineHeight: normalize(20),
    fontFamily: tokens.fontFamily.bold,
    color: COLORS.text,
  },
  stateText: {
    marginTop: normalize(10),
    textAlign: 'center',
    fontSize: normalize(13),
    lineHeight: normalize(20),
    fontFamily: tokens.fontFamily.regular,
    color: COLORS.textSecondary,
  },
  retryButton: {
    marginTop: normalize(14),
    paddingHorizontal: normalize(16),
    paddingVertical: normalize(12),
    borderRadius: normalize(12),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  retryLabel: {
    fontSize: normalize(13),
    fontFamily: tokens.fontFamily.medium,
    color: COLORS.text,
  },
  inputRow: { flexDirection: 'row', alignItems: 'center' },
  input: {
    flex: 1,
    height: normalize(48),
    paddingHorizontal: normalize(13),
    borderRadius: normalize(12),
    borderWidth: 1,
    borderColor: COLORS.border,
    fontSize: normalize(13),
    fontFamily: tokens.fontFamily.regular,
    color: COLORS.text,
  },
  addButton: {
    marginLeft: normalize(8),
    width: normalize(48),
    height: normalize(48),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: normalize(12),
    backgroundColor: COLORS.primary,
  },
  addButtonDisabled: { backgroundColor: COLORS.disabled },
});
