import { StyleSheet } from 'react-native';
import { normalize } from '../../../utils/normalize';
import { tokens } from '../../../theme/tokens';

export const COLORS = tokens.colors;

export const styles = StyleSheet.create({
  // 좁은 화면에서 카드 테두리까지 겹치면 글 쓸 자리가 그만큼 줄어든다.
  // 웹의 회색 바탕 + 흰 카드 대신 앱 글쓰기 화면처럼 흰 바탕 한 장으로 둔다.
  container: { flex: 1, backgroundColor: tokens.colors.white },
  header: {
    backgroundColor: tokens.colors.white,
    height: normalize(56),
    paddingHorizontal: normalize(16),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: tokens.colors.border,
  },
  headerText: { flex: 1, alignItems: 'center' },
  headerSpacer: { width: normalize(24) },
  headerTitle: {
    fontSize: normalize(17),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.text,
  },
  // 웹 CreatePostHeader의 부제. 무엇을 쓰는 곳인지 한 줄로 알린다.
  headerSubtitle: {
    marginTop: normalize(2),
    fontSize: normalize(11.5),
    fontFamily: tokens.fontFamily.regular,
    color: tokens.colors.textSecondary,
  },
  // 웹은 카드 두 장으로 나누지만 앱은 제목만 놓는다. 라벨(14)보다 한 단계 위다.
  section: {
    fontSize: normalize(17),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.text,
    letterSpacing: -0.3,
  },
  sectionGap: { marginTop: normalize(18) },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: normalize(10),
    marginBottom: normalize(8),
  },
  importPlanButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
    paddingHorizontal: normalize(14),
    paddingVertical: normalize(10),
    borderRadius: normalize(12),
    backgroundColor: tokens.colors.primary,
  },
  importPlanButtonText: {
    fontSize: normalize(13),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.white,
  },
  fieldLabelRow: {
    marginTop: normalize(8),
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  fieldLabelGap: { marginTop: normalize(18) },
  fieldLabel: {
    fontSize: normalize(14),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.textLabel,
  },
  requiredMark: {
    fontSize: normalize(13),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.tones.danger.fg,
  },
  // 웹은 여행지와 기간 앞칸을 테두리 상자가 아니라 밑줄로 둔다. 그래야 바로
  // 옆 파란 알약이 먼저 눈에 든다.
  underlineField: {
    marginTop: normalize(2),
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(10),
    minHeight: normalize(46),
    paddingBottom: normalize(8),
    borderBottomWidth: 2,
    borderBottomColor: tokens.colors.border,
  },
  underlineValue: {
    flex: 1,
    fontSize: normalize(16),
    fontFamily: tokens.fontFamily.medium,
    color: tokens.colors.text,
  },
  underlinePlaceholder: {
    fontFamily: tokens.fontFamily.regular,
    color: '#CCCCCC',
  },
  durationRow: {
    marginTop: normalize(2),
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(12),
  },
  durationBadge: {
    flex: 1,
    minHeight: normalize(46),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: normalize(16),
    backgroundColor: tokens.colors.primary,
  },
  durationBadgeText: {
    fontSize: normalize(16),
    letterSpacing: -0.4,
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.white,
  },
  fieldHint: {
    marginTop: normalize(10),
    fontSize: normalize(11),
    fontFamily: tokens.fontFamily.medium,
    color: tokens.colors.textMuted,
  },
  divider: {
    marginTop: normalize(12),
    marginBottom: normalize(4),
    height: 1,
    backgroundColor: tokens.colors.borderLight,
  },
  subSection: {
    fontSize: normalize(15),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.text,
  },
  // 일정을 아직 안 붙였을 때. 점선으로 "여기 채워진다"를 알린다.
  scheduleEmpty: {
    alignItems: 'center',
    gap: normalize(8),
    paddingVertical: normalize(32),
    paddingHorizontal: normalize(16),
    borderRadius: normalize(12),
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: tokens.colors.border,
  },
  scheduleEmptyTitle: {
    fontSize: normalize(14),
    fontFamily: tokens.fontFamily.medium,
    color: tokens.colors.textSecondary,
  },
  scheduleEmptySub: {
    textAlign: 'center',
    fontSize: normalize(12),
    lineHeight: normalize(18),
    fontFamily: tokens.fontFamily.regular,
    color: tokens.colors.textMuted,
  },
  memoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(10),
    paddingVertical: normalize(4),
  },
  memoBox: {
    width: normalize(20),
    height: normalize(20),
    borderRadius: normalize(6),
    borderWidth: 1.5,
    borderColor: tokens.colors.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  memoBoxOn: {
    backgroundColor: tokens.colors.primary,
    borderColor: tokens.colors.primary,
  },
  memoTextWrap: { flex: 1 },
  memoLabel: {
    fontSize: normalize(13),
    fontFamily: tokens.fontFamily.medium,
    color: tokens.colors.text,
  },
  memoHint: {
    marginTop: normalize(2),
    fontSize: normalize(11),
    fontFamily: tokens.fontFamily.regular,
    color: tokens.colors.textMuted,
  },
  body: { padding: normalize(16), gap: normalize(20) },
  // 절을 묶기만 하고 테두리는 두지 않는다. 화면 양옆 여백은 body의 16 하나뿐이라
  // 입력칸과 편집기가 카드 안에 있을 때보다 양쪽으로 16씩 더 넓어진다.
  group: { gap: normalize(8) },
  /** 테두리가 없어진 자리를 대신해 절 경계를 알린다. 첫 절에는 붙이지 않는다. */
  groupDivider: {
    paddingTop: normalize(20),
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderLight,
  },
  label: {
    marginTop: normalize(8),
    fontSize: normalize(14),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.textLabel,
  },
  /** 앞 칸과 붙어 보이지 않게 한 칸 더 띄운다. */
  labelGap: { marginTop: normalize(16) },
  dayCountRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: normalize(14),
    paddingVertical: normalize(10),
    borderRadius: normalize(12),
    borderWidth: 1,
    borderColor: tokens.colors.border,
    backgroundColor: tokens.colors.white,
  },
  dayCountButton: {
    width: normalize(34),
    height: normalize(34),
    borderRadius: normalize(10),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.colors.surface,
  },
  dayCountButtonText: {
    fontSize: normalize(18),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.text,
  },
  dayCountValue: {
    fontSize: normalize(14),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.text,
  },
  planPickerTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: normalize(14),
    borderRadius: normalize(12),
    borderWidth: 1,
    borderColor: tokens.colors.borderStrong,
    borderStyle: 'dashed',
    backgroundColor: tokens.colors.surface,
  },
  planPickerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(12),
    flex: 1,
  },
  planPickerIconWrap: {
    width: normalize(38),
    height: normalize(38),
    borderRadius: normalize(10),
    backgroundColor: tokens.colors.primarySurface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  planPickerTitle: {
    fontSize: normalize(14),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.text,
  },
  planPickerSubtitle: {
    marginTop: normalize(2),
    fontSize: normalize(12),
    fontFamily: tokens.fontFamily.regular,
    color: tokens.colors.textSecondary,
  },
  selectedPlanCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: normalize(14),
    borderRadius: normalize(12),
    borderWidth: 1,
    borderColor: tokens.colors.primary,
    backgroundColor: tokens.colors.primarySurface,
  },
  selectedPlanLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(12),
    flex: 1,
    marginRight: normalize(8),
  },
  selectedPlanIconWrap: {
    width: normalize(38),
    height: normalize(38),
    borderRadius: normalize(10),
    backgroundColor: tokens.colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedPlanInfo: {
    flex: 1,
  },
  selectedPlanName: {
    fontSize: normalize(14),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.text,
  },
  selectedPlanMeta: {
    marginTop: normalize(2),
    fontSize: normalize(12),
    fontFamily: tokens.fontFamily.regular,
    color: tokens.colors.primary,
  },
  planCardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  changePlanButton: {
    paddingHorizontal: normalize(12),
    paddingVertical: normalize(6),
    borderRadius: normalize(8),
    backgroundColor: tokens.colors.white,
    borderWidth: 1,
    borderColor: tokens.colors.border,
  },
  changePlanButtonText: {
    fontSize: normalize(12),
    fontFamily: tokens.fontFamily.semibold,
    color: tokens.colors.textSecondary,
  },
  planCard: {
    minHeight: normalize(64),
    borderWidth: 1,
    borderColor: tokens.colors.border,
    borderRadius: normalize(12),
    padding: normalize(14),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  planCardSelected: {
    borderColor: tokens.colors.primary,
    backgroundColor: tokens.colors.primarySurface,
  },
  planName: {
    fontSize: normalize(15),
    fontFamily: tokens.fontFamily.semibold,
    color: tokens.colors.text,
  },
  planDate: {
    marginTop: normalize(4),
    fontSize: normalize(12),
    fontFamily: tokens.fontFamily.regular,
    color: tokens.colors.textSecondary,
  },
  emptyText: {
    paddingVertical: normalize(16),
    fontSize: normalize(13),
    fontFamily: tokens.fontFamily.medium,
    color: tokens.colors.textSecondary,
    textAlign: 'center',
  },
  itineraryPreview: {
    borderWidth: 1,
    borderColor: tokens.colors.border,
    borderRadius: normalize(12),
    overflow: 'hidden',
  },
  previewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: normalize(14),
    paddingVertical: normalize(10),
    backgroundColor: tokens.colors.surface,
  },
  previewTitle: {
    fontSize: normalize(13),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.textLabel,
  },
  durationPill: {
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(3),
    borderRadius: tokens.radius.round,
    backgroundColor: tokens.colors.sub,
  },
  durationPillText: {
    fontSize: normalize(12),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.primary,
  },
  previewDay: {
    flexDirection: 'row',
    gap: normalize(10),
    padding: normalize(12),
    borderTopWidth: 1,
    borderTopColor: tokens.colors.borderLight,
  },
  previewDayLabel: {
    alignSelf: 'flex-start',
    paddingHorizontal: normalize(7),
    paddingVertical: normalize(4),
    borderRadius: normalize(6),
    backgroundColor: tokens.colors.sub,
  },
  previewDayText: {
    fontSize: normalize(11),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.primary,
  },
  previewPlaces: { flex: 1 },
  previewPlace: {
    fontSize: normalize(13),
    fontFamily: tokens.fontFamily.regular,
    color: tokens.colors.textLabel,
  },
  // 줄 간격을 행 사이(gap)가 아니라 행 안쪽(timelineContent)에 둔다.
  // 그래야 세로선이 그 간격까지 덮어 다음 번호에 닿는다.
  timelineItemRow: {
    flexDirection: 'row',
    gap: normalize(10),
  },
  timelineTrack: {
    alignItems: 'center',
    width: normalize(20),
  },
  timelineBadge: {
    width: normalize(18),
    height: normalize(18),
    borderRadius: normalize(9),
    backgroundColor: tokens.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineBadgeText: {
    fontSize: normalize(10),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.white,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    minHeight: normalize(10),
    borderRadius: 1,
    backgroundColor: tokens.colors.border,
    // 위는 번호에서 살짝 떼고, 아래는 다음 번호에 그대로 닿게 둔다.
    marginTop: normalize(3),
  },
  timelineContent: {
    flex: 1,
    paddingBottom: normalize(6),
  },
  // 뒤에 장소가 더 있을 때만 아래를 벌린다. 그 여백을 세로선이 채운다.
  timelineContentLinked: {
    paddingBottom: normalize(12),
  },
  timelinePlaceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  timelinePlaceName: {
    fontSize: normalize(13),
    fontFamily: tokens.fontFamily.semibold,
    color: tokens.colors.text,
    flexShrink: 1,
  },
  timelineTimeChip: {
    paddingHorizontal: normalize(6),
    paddingVertical: normalize(1),
    borderRadius: normalize(4),
    backgroundColor: tokens.colors.surface,
    borderWidth: 1,
    borderColor: tokens.colors.borderLight,
  },
  timelineTimeText: {
    fontSize: normalize(10),
    fontFamily: tokens.fontFamily.medium,
    color: tokens.colors.textMuted,
  },
  timelinePlaceDesc: {
    marginTop: normalize(2),
    fontSize: normalize(11.5),
    fontFamily: tokens.fontFamily.regular,
    color: tokens.colors.textSecondary,
  },
  previewMore: {
    fontSize: normalize(12),
    fontFamily: tokens.fontFamily.regular,
    color: tokens.colors.textMuted,
  },
  formatToolbar: {
    marginTop: normalize(6),
  },
  toolbarScroll: {
    flexDirection: 'row',
    gap: normalize(6),
    paddingVertical: normalize(4),
  },
  toolBtn: {
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
    borderRadius: normalize(6),
    backgroundColor: tokens.colors.surface,
    borderWidth: 1,
    borderColor: tokens.colors.border,
  },
  toolBtnTextBold: { fontFamily: tokens.fontFamily.bold },
  toolBtnText: {
    fontSize: normalize(12),
    fontFamily: tokens.fontFamily.medium,
    color: tokens.colors.textSecondary,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
    marginHorizontal: normalize(16),
    marginTop: normalize(12),
    paddingHorizontal: normalize(12),
    height: normalize(40),
    backgroundColor: tokens.colors.surface,
    borderRadius: normalize(8),
    borderWidth: 1,
    borderColor: tokens.colors.border,
  },
  searchInput: {
    flex: 1,
    fontSize: normalize(13),
    fontFamily: tokens.fontFamily.regular,
    color: tokens.colors.text,
    paddingVertical: 0,
  },
  modalList: {
    marginTop: normalize(8),
  },
  modalListContent: {
    paddingHorizontal: normalize(16),
    paddingVertical: normalize(8),
    gap: normalize(8),
  },
  input: {
    minHeight: normalize(48),
    borderWidth: 1,
    borderColor: tokens.colors.borderStrong,
    borderRadius: normalize(10),
    paddingHorizontal: normalize(12),
    fontSize: normalize(14),
    fontFamily: tokens.fontFamily.regular,
    color: tokens.colors.text,
  },
  contentInput: { minHeight: normalize(120), paddingTop: normalize(12) },
  imageSelectButton: {
    minHeight: normalize(46),
    borderWidth: 1,
    borderColor: tokens.colors.primary,
    borderRadius: normalize(10),
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageSelectText: {
    fontSize: normalize(14),
    fontFamily: tokens.fontFamily.semibold,
    color: tokens.colors.primary,
  },
  selectedImageName: {
    fontSize: normalize(12),
    fontFamily: tokens.fontFamily.regular,
    color: tokens.colors.textSecondary,
  },
  footer: {
    padding: normalize(16),
    borderTopWidth: 1,
    borderTopColor: tokens.colors.border,
  },
  submitButton: {
    minHeight: normalize(52),
    borderRadius: normalize(12),
    backgroundColor: tokens.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitDisabled: { backgroundColor: tokens.colors.disabled },
  submitText: {
    fontSize: normalize(15),
    fontFamily: tokens.fontFamily.bold,
    color: tokens.colors.white,
  },
  submitTextOff: { color: tokens.colors.textTertiary },
});

