import { StyleSheet, Dimensions } from 'react-native';
import { normalize } from '../../../utils/normalize';
import { tokens } from '../../../theme/tokens';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const COLORS = {
  primary: tokens.colors.primary,
  primaryTint: tokens.colors.primaryTint,
  sub: tokens.colors.sub,
  background: tokens.colors.background,
  card: tokens.colors.white,
  text: tokens.colors.text,
  textSecondary: tokens.colors.textSecondary,
  placeholder: tokens.colors.textTertiary,
  border: tokens.colors.border,
  borderLight: tokens.colors.borderLight,
  white: tokens.colors.white,
  error: tokens.tones.danger.fg,
  surface: tokens.colors.surface,
};

export const FONTS = tokens.fontFamily;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.surface,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
  },
  loadErrorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    paddingHorizontal: normalize(32),
  },
  loadErrorText: {
    fontFamily: FONTS.medium,
    fontSize: normalize(15),
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: normalize(16),
  },
  loadErrorButton: {
    backgroundColor: COLORS.borderLight,
    borderRadius: normalize(12),
    paddingHorizontal: normalize(24),
    height: normalize(44),
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadErrorButtonText: {
    fontFamily: FONTS.semibold,
    fontSize: normalize(14),
    color: COLORS.textSecondary,
  },
  scrollContainer: {
    paddingBottom: normalize(40),
  },

  profileCard: {
    backgroundColor: COLORS.white,
    borderRadius: normalize(16),
    padding: normalize(20),
    marginHorizontal: normalize(16),
    marginTop: normalize(16),
  },
  profileHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(20),
  },
  avatarContainer: {
    position: 'relative',
    marginRight: normalize(16),
  },
  avatarImage: {
    width: normalize(76),
    height: normalize(76),
    borderRadius: normalize(38),
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  avatarPlaceholder: {
    width: normalize(76),
    height: normalize(76),
    borderRadius: normalize(38),
    borderWidth: 2,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.borderLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingsButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: COLORS.primary,
    width: normalize(24),
    height: normalize(24),
    borderRadius: normalize(12),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.white,
  },
  profileTextInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  nicknameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: normalize(4),
    gap: normalize(6),
  },
  nicknameText: {
    fontSize: normalize(22),
    fontFamily: FONTS.bold,
    fontWeight: '800',
    color: COLORS.text,
  },
  levelBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(2),
    borderRadius: normalize(12),
    gap: normalize(3),
  },
  levelBadgeText: {
    fontSize: normalize(10),
    color: COLORS.white,
    fontWeight: 'bold',
  },
  emailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  emailText: {
    fontSize: normalize(12),
    color: COLORS.textSecondary,
  },
  emailDivider: {
    fontSize: normalize(12),
    color: COLORS.placeholder,
    marginHorizontal: normalize(6),
  },
  genderAgeBadge: {
    backgroundColor: COLORS.borderLight,
    paddingHorizontal: normalize(6),
    paddingVertical: normalize(2),
    borderRadius: normalize(4),
  },
  genderAgeBadgeText: {
    fontSize: normalize(10),
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  experienceSection: {
    marginBottom: normalize(16),
  },
  experienceLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(6),
  },
  experienceTitle: {
    fontSize: normalize(12),
    color: COLORS.primary,
    fontWeight: 'bold',
  },
  experienceValue: {
    fontSize: normalize(11),
    color: COLORS.placeholder,
  },
  progressBarTrack: {
    height: normalize(6),
    backgroundColor: COLORS.border,
    borderRadius: normalize(3),
    width: '100%',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: COLORS.primary,
    borderRadius: normalize(3),
  },
  tagSection: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: normalize(6),
    marginBottom: normalize(20),
  },
  interestTag: {
    backgroundColor: COLORS.borderLight,
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(4),
    borderRadius: normalize(6),
  },
  interestTagText: {
    fontSize: normalize(11),
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  statsSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
    paddingTop: normalize(16),
  },
  statBlock: {
    alignItems: 'center',
  },
  statNumber: {
    fontSize: normalize(20),
    color: COLORS.primary,
    fontWeight: 'bold',
    marginBottom: normalize(2),
  },
  statLabel: {
    fontSize: normalize(11),
    color: COLORS.textSecondary,
  },

  achievementCard: {
    backgroundColor: COLORS.surface,
    borderRadius: normalize(16),
    padding: normalize(20),
    marginHorizontal: normalize(16),
    marginTop: normalize(16),
    borderWidth: 1,
    borderColor: COLORS.placeholder,
    borderStyle: 'dashed',
  },
  achievementHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(16),
  },
  achievementTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  achievementTitle: {
    fontSize: normalize(16),
    fontWeight: 'bold',
    color: COLORS.text,
  },
  achievementProgressBadge: {
    backgroundColor: COLORS.primaryTint,
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(2),
    borderRadius: normalize(12),
  },
  achievementProgressText: {
    fontSize: normalize(10),
    color: COLORS.primary,
    fontWeight: 'bold',
  },
  badgeList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: normalize(8),
  },
  achievementBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
    borderRadius: normalize(8),
    gap: normalize(4),
  },
  badgeText: {
    fontSize: normalize(11),
    fontWeight: 'bold',
  },

  editDialogCard: {
    backgroundColor: COLORS.white,
    borderRadius: normalize(24),
    width: SCREEN_WIDTH * 0.9,
    height: normalize(500),
    overflow: 'hidden',
    alignSelf: 'center',
    ...tokens.shadows.md,
  },
  editDialogHeader: {
    height: normalize(110),
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    position: 'relative',
    paddingTop: normalize(16),
    width: '100%',
    zIndex: 10,
    elevation: 5,
  },
  closeModalButton: {
    position: 'absolute',
    top: normalize(16),
    right: normalize(16),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    width: normalize(28),
    height: normalize(28),
    borderRadius: normalize(14),
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarEditContainer: {
    position: 'absolute',
    bottom: normalize(-40),
    alignSelf: 'center',
    zIndex: 11,
  },
  avatarEditImage: {
    width: normalize(90),
    height: normalize(90),
    borderRadius: normalize(45),
    borderWidth: 4,
    borderColor: COLORS.white,
  },
  avatarEditPlaceholder: {
    width: normalize(90),
    height: normalize(90),
    borderRadius: normalize(45),
    borderWidth: 4,
    borderColor: COLORS.white,
    backgroundColor: COLORS.borderLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: COLORS.primary,
    width: normalize(26),
    height: normalize(26),
    borderRadius: normalize(13),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.white,
  },
  editDialogBody: {
    paddingHorizontal: normalize(24),
    paddingTop: normalize(52),
    paddingBottom: normalize(60),
    zIndex: 1,
  },
  scrollArea: {
    flex: 1,
    zIndex: 1,
  },
  editDialogTitle: {
    fontSize: normalize(20),
    fontWeight: 'bold',
    color: COLORS.text,
    textAlign: 'center',
    marginBottom: normalize(4),
  },
  editDialogSubtitle: {
    fontSize: normalize(12),
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: normalize(24),
  },
  inputGroup: {
    marginBottom: normalize(16),
  },
  inputLabel: {
    fontSize: normalize(13),
    fontWeight: '700',
    color: COLORS.textSecondary,
    marginBottom: normalize(8),
  },
  textInput: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: normalize(12),
    paddingHorizontal: normalize(16),
    height: normalize(44),
    fontSize: normalize(14),
    color: COLORS.text,
  },
  visibilityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: normalize(12),
  },
  visibilityDescription: {
    flex: 1,
    fontSize: normalize(12),
    color: COLORS.textSecondary,
  },

  pickerField: {
    justifyContent: 'center',
  },
  pickerFieldText: {
    fontSize: normalize(14),
    color: COLORS.text,
  },
  pickerFieldPlaceholder: {
    color: COLORS.placeholder,
  },
  textInputDisabled: {
    backgroundColor: COLORS.borderLight,
    color: COLORS.placeholder,
    borderColor: COLORS.border,
  },
  rowInputWrap: {
    flexDirection: 'row',
    gap: normalize(10),
  },
  checkButton: {
    backgroundColor: COLORS.borderLight,
    borderRadius: normalize(12),
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: normalize(16),
    height: normalize(44),
  },
  checkButtonText: {
    fontSize: normalize(13),
    fontWeight: 'bold',
    color: COLORS.textSecondary,
  },
  twoColumnRow: {
    flexDirection: 'row',
    marginBottom: normalize(16),
  },
  genderSelectTrack: {
    flexDirection: 'row',
    backgroundColor: COLORS.borderLight,
    borderRadius: normalize(12),
    height: normalize(44),
    padding: normalize(2),
    width: '100%',
  },
  genderOptionButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: normalize(10),
  },
  genderOptionActive: {
    backgroundColor: COLORS.primary,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  genderOptionText: {
    fontSize: normalize(13),
    color: COLORS.placeholder,
    fontWeight: '500',
  },
  genderOptionActiveText: {
    color: COLORS.white,
    fontWeight: 'bold',
  },
  actionNavButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: normalize(12),
    paddingHorizontal: normalize(16),
    height: normalize(44),
  },
  actionNavButtonDisabled: {
    backgroundColor: COLORS.borderLight,
    borderColor: COLORS.border,
    opacity: 0.6,
  },
  actionNavButtonText: {
    fontSize: normalize(13),
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  saveButton: {
    backgroundColor: COLORS.primary,
    borderRadius: normalize(14),
    height: normalize(48),
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  saveButtonText: {
    fontSize: normalize(15),
    fontWeight: 'bold',
    color: COLORS.white,
  },
  resignLinkButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: normalize(10),
    marginTop: normalize(10),
    marginBottom: normalize(16),
  },
  resignLinkText: {
    fontSize: normalize(13),
    color: COLORS.error,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fadeOverlay: {
    width: '100%',
    height: normalize(45),
  },
  fadeOverlayContainer: {
    position: 'absolute',
    bottom: normalize(80),
    left: 0,
    right: 0,
    height: normalize(45),
    zIndex: 2,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  scrollHintContainer: {
    position: 'absolute',
    bottom: normalize(2),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: normalize(4),
    backgroundColor: 'rgba(19, 68, 255, 0.08)',
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(3),
    borderRadius: normalize(10),
  },
  scrollHintText: {
    fontSize: normalize(10),
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  keyboardAvoidingWrapper: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fixedBottomArea: {
    paddingHorizontal: normalize(24),
    paddingBottom: normalize(20),
    paddingTop: normalize(12),
    backgroundColor: COLORS.white,
    zIndex: 3,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
    width: '100%',
  },

  itineraryDetailCard: {
    backgroundColor: COLORS.white,
    borderRadius: normalize(16),
    padding: normalize(20),
    marginHorizontal: normalize(16),
    marginTop: normalize(16),
  },
  itineraryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(16),
  },
  itineraryTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  itineraryTitle: {
    fontSize: normalize(16),
    fontWeight: 'bold',
    color: COLORS.text,
  },
  itineraryManageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: normalize(8),
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(5),
    backgroundColor: COLORS.white,
  },
  itineraryManageText: {
    fontSize: normalize(11),
    color: COLORS.textSecondary,
    fontWeight: 'bold',
  },
  dashedPlanBox: {
    borderWidth: 1,
    borderColor: COLORS.placeholder,
    borderStyle: 'dashed',
    borderRadius: normalize(12),
    paddingVertical: normalize(32),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: normalize(16),
  },
  noPlanText: {
    fontSize: normalize(12),
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: normalize(10),
  },
  createPlanLink: {
    fontSize: normalize(13),
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  pastRecordBox: {
    backgroundColor: COLORS.surface,
    borderRadius: normalize(12),
    padding: normalize(16),
    marginTop: normalize(16),
  },
  pastRecordTitle: {
    fontSize: normalize(13),
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: normalize(16),
  },
  noPastRecordText: {
    fontSize: normalize(12),
    color: COLORS.placeholder,
    textAlign: 'center',
    paddingVertical: normalize(16),
  },

  itineraryCardWrapper: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: normalize(12),
    width: '100%',
    padding: normalize(16),
    marginBottom: normalize(12),
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(8),
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  ddayBadge: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: normalize(6),
    paddingVertical: normalize(2),
    borderRadius: normalize(4),
  },
  ddayText: {
    fontSize: normalize(10),
    fontWeight: 'bold',
    color: COLORS.white,
  },
  statusText: {
    fontSize: normalize(11),
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  cardTitleText: {
    fontSize: normalize(18),
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: normalize(4),
  },
  dateInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(16),
  },
  datePeriodText: {
    fontSize: normalize(12),
    color: COLORS.textSecondary,
  },
  checklistContainer: {
    backgroundColor: COLORS.surface,
    borderRadius: normalize(12),
    padding: normalize(12),
  },
  checklistHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(8),
  },
  checklistTitle: {
    fontSize: normalize(10),
    fontWeight: '700',
    color: COLORS.textSecondary,
    letterSpacing: 0.5,
  },
  checklistProgressText: {
    fontSize: normalize(10),
    color: COLORS.textSecondary,
    fontWeight: '600',
  },
  taskItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: normalize(6),
  },
  taskText: {
    fontSize: normalize(13),
    color: '#374151',
    flex: 1,
  },
  taskTextCompleted: {
    color: COLORS.placeholder,
    textDecorationLine: 'line-through',
  },
  addTaskButton: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderStyle: 'dashed',
    borderRadius: normalize(8),
    paddingVertical: normalize(8),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: normalize(8),
    backgroundColor: COLORS.white,
  },
  addTaskButtonText: {
    fontSize: normalize(12),
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  sectionSubtitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(12),
    gap: normalize(4),
  },
  sectionSubtitleText: {
    fontSize: normalize(13),
    fontWeight: 'bold',
    color: COLORS.textSecondary,
  },

  pastPlansContainer: {
    gap: normalize(10),
  },
  pastPlanItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: normalize(12),
    padding: normalize(14),
    width: '100%',
  },
  pastPlanLeft: {
    flex: 1,
  },
  pastPlanTitleText: {
    fontSize: normalize(15),
    fontWeight: 'bold',
    color: '#374151',
    marginBottom: normalize(4),
  },
  pastPlanDateText: {
    fontSize: normalize(12),
    color: COLORS.placeholder,
  },
  pastPlanBadge: {
    backgroundColor: COLORS.borderLight,
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(4),
    borderRadius: normalize(6),
  },
  pastPlanBadgeText: {
    fontSize: normalize(10),
    color: COLORS.textSecondary,
    fontWeight: 'bold',
  },
  sharedBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: '#F97316',
    borderTopRightRadius: normalize(15),
    borderBottomLeftRadius: normalize(16),
    paddingHorizontal: normalize(12),
    paddingVertical: normalize(6),
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 2,
  },
  sharedBadgeText: {
    fontSize: normalize(10),
    fontWeight: 'bold',
    color: COLORS.white,
  },

  editModeHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  editActionSelectAll: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    borderRadius: normalize(8),
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
  },
  selectAllCheckSquare: {
    width: normalize(12),
    height: normalize(12),
    borderWidth: 1,
    borderColor: COLORS.placeholder,
    borderRadius: normalize(3),
    marginRight: normalize(4),
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectAllCheckSquareChecked: {
    backgroundColor: COLORS.textSecondary,
    borderColor: COLORS.textSecondary,
  },
  editActionSelectAllText: {
    fontSize: normalize(11),
    color: COLORS.textSecondary,
    fontWeight: 'bold',
  },
  editActionDeleteSelected: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FEE2E2',
    backgroundColor: '#FEF2F2',
    borderRadius: normalize(8),
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
  },
  editActionDeleteSelectedText: {
    fontSize: normalize(11),
    color: COLORS.error,
    fontWeight: 'bold',
  },
  editActionCancel: {
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
  },
  editActionCancelText: {
    fontSize: normalize(11),
    color: COLORS.textSecondary,
    fontWeight: 'bold',
  },
  cardCheckboxWrap: {
    marginRight: normalize(6),
  },
  cardCheckboxSquare: {
    width: normalize(16),
    height: normalize(16),
    borderWidth: 1,
    borderColor: COLORS.placeholder,
    borderRadius: normalize(4),
    alignItems: 'center',
    justifyContent: 'center',    backgroundColor: COLORS.white,
  },
  editSubToolbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    paddingHorizontal: normalize(12),
    paddingVertical: normalize(8),
    borderRadius: normalize(12),
    marginBottom: normalize(16),
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: normalize(16),
    height: normalize(52),
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  backButton: {
    padding: normalize(4),
  },
  headerTitle: {
    fontSize: normalize(18),
    fontFamily: FONTS.bold,
    fontWeight: 'bold',
    color: COLORS.text,
  },

  sectionTabsWrap: {
    marginTop: normalize(16),
    marginHorizontal: normalize(16),
    borderRadius: tokens.radius.l,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  tripTabs: {
    marginBottom: normalize(14),
    marginHorizontal: normalize(-4),
    borderBottomColor: COLORS.borderLight,
  },
  dashedPlanIcon: {
    marginBottom: normalize(8),
  },

  headerSpacer: {
    width: 28,
  },
  cardInfoStatic: {
    pointerEvents: 'none',
  },
  ddayBadgeShared: {
    backgroundColor: '#F97316',
  },
  dateIconSpacing: {
    marginRight: 4,
  },
  checklistHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checklistIconSpacing: {
    marginRight: 6,
  },
  taskIconSpacing: {
    marginRight: 8,
  },
  sharedBadgeIconSpacing: {
    marginRight: 2,
  },
  achievementCardDisabled: {
    opacity: 0.6,
  },
  disabledOpacity: {
    opacity: 0.5,
  },
  iconSpacingSmall: {
    marginRight: 4,
  },
  pastPlanItemSelectedBorder: {
    borderWidth: 2,
  },
  pastPlanRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  pastPlanTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  pastPlanBadgeShared: {
    backgroundColor: COLORS.borderLight,
    borderColor: COLORS.border,
    borderWidth: 1,
  },
  pastPlanMenuButton: {
    padding: 4,
  },
  flex1: {
    flex: 1,
  },
  flex1MarginRight12: {
    flex: 1,
    marginRight: 12,
  },
});
