import { StyleSheet, Dimensions } from 'react-native';
import { normalize } from '../../../utils/normalize';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const COLORS = {
  primary: '#1344FF',
  sub: '#E8EDFF',
  background: '#FFFFFF',
  card: '#FFFFFF',
  text: '#111827',
  textSecondary: '#6B7280',
  placeholder: '#9CA3AF',
  border: '#E5E7EB',
  borderLight: '#F3F4F6',
  white: '#FFFFFF',
  error: '#EF4444',
  surface: '#F9FAFB',
};

export const FONTS = {
  regular: 'Pretendard-Regular',
  medium: 'Pretendard-Medium',
  semibold: 'Pretendard-SemiBold',
  bold: 'Pretendard-Bold',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  scrollContainer: {
    paddingBottom: normalize(40),
  },

  /* ── New Web Style Profile ── */
  profileCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: normalize(16),
    padding: normalize(20),
    marginHorizontal: normalize(16),
    marginTop: normalize(16),
    borderWidth: 1,
    borderColor: '#EAECEF',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  profileHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(20),
  },
  avatarContainer: {
    position: 'relative',
    marginRight: normalize(16),
  },
  avatarImage: {
    width: normalize(76),
    height: normalize(76),
    borderRadius: normalize(38),
    borderWidth: 2,
    borderColor: '#1344FF',
  },
  avatarPlaceholder: {
    width: normalize(76),
    height: normalize(76),
    borderRadius: normalize(38),
    borderWidth: 2,
    borderColor: '#1344FF',
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingsButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#1344FF',
    width: normalize(24),
    height: normalize(24),
    borderRadius: normalize(12),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  profileTextInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  nicknameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: normalize(4),
    gap: normalize(6),
  },
  nicknameText: {
    fontSize: normalize(22),
    fontFamily: FONTS.bold,
    fontWeight: '800',
    color: '#111827',
  },
  levelBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1344FF',
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(2),
    borderRadius: normalize(12),
    gap: normalize(3),
  },
  levelBadgeText: {
    fontSize: normalize(10),
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  emailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  emailText: {
    fontSize: normalize(12),
    color: '#6B7280',
  },
  emailDivider: {
    fontSize: normalize(12),
    color: '#D1D5DB',
    marginHorizontal: normalize(6),
  },
  genderAgeBadge: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: normalize(6),
    paddingVertical: normalize(2),
    borderRadius: normalize(4),
  },
  genderAgeBadgeText: {
    fontSize: normalize(10),
    color: '#4B5563',
    fontWeight: '500',
  },
  experienceSection: {
    marginBottom: normalize(16),
  },
  experienceLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(6),
  },
  experienceTitle: {
    fontSize: normalize(12),
    color: '#1344FF',
    fontWeight: 'bold',
  },
  experienceValue: {
    fontSize: normalize(11),
    color: '#9CA3AF',
  },
  progressBarTrack: {
    height: normalize(6),
    backgroundColor: '#E5E7EB',
    borderRadius: normalize(3),
    width: '100%',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#1344FF',
    borderRadius: normalize(3),
  },
  tagSection: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: normalize(6),
    marginBottom: normalize(20),
  },
  interestTag: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(4),
    borderRadius: normalize(6),
  },
  interestTagText: {
    fontSize: normalize(11),
    color: '#4B5563',
    fontWeight: '500',
  },
  statsSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    paddingTop: normalize(16),
  },
  statBlock: {
    alignItems: 'center',
  },
  statNumber: {
    fontSize: normalize(20),
    color: '#1344FF',
    fontWeight: 'bold',
    marginBottom: normalize(2),
  },
  statLabel: {
    fontSize: normalize(11),
    color: '#6B7280',
  },

  /* ── Achievements Area ── */
  achievementCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: normalize(16),
    padding: normalize(20),
    marginHorizontal: normalize(16),
    marginTop: normalize(16),
    borderWidth: 1,
    borderColor: '#EAECEF',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
  },
  achievementHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(16),
  },
  achievementTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  achievementTitle: {
    fontSize: normalize(16),
    fontWeight: 'bold',
    color: '#111827',
  },
  achievementProgressBadge: {
    backgroundColor: '#E8F0FE',
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(2),
    borderRadius: normalize(12),
  },
  achievementProgressText: {
    fontSize: normalize(10),
    color: '#1A73E8',
    fontWeight: 'bold',
  },
  badgeList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: normalize(8),
  },
  achievementBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
    borderRadius: normalize(8),
    gap: normalize(4),
  },
  badgeText: {
    fontSize: normalize(11),
    fontWeight: 'bold',
  },

  /* ── Edit Profile Dialog Styles ── */
  editDialogCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: normalize(24),
    width: SCREEN_WIDTH * 0.9,
    height: normalize(500),
    overflow: 'hidden',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 15,
    alignSelf: 'center',
  },
  editDialogHeader: {
    height: normalize(110),
    backgroundColor: '#1344FF',
    alignItems: 'center',
    position: 'relative',
    paddingTop: normalize(16),
    width: '100%',
    zIndex: 10,
    elevation: 5,
  },
  closeModalButton: {
    position: 'absolute',
    top: normalize(16),
    right: normalize(16),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    width: normalize(28),
    height: normalize(28),
    borderRadius: normalize(14),
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarEditContainer: {
    position: 'absolute',
    bottom: normalize(-40),
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 6,
    zIndex: 11,
  },
  avatarEditImage: {
    width: normalize(90),
    height: normalize(90),
    borderRadius: normalize(45),
    borderWidth: 4,
    borderColor: '#FFFFFF',
  },
  avatarEditPlaceholder: {
    width: normalize(90),
    height: normalize(90),
    borderRadius: normalize(45),
    borderWidth: 4,
    borderColor: '#FFFFFF',
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#1344FF',
    width: normalize(26),
    height: normalize(26),
    borderRadius: normalize(13),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  editDialogBody: {
    paddingHorizontal: normalize(24),
    paddingTop: normalize(52),
    paddingBottom: normalize(60),
    zIndex: 1,
  },
  scrollArea: {
    flex: 1,
    zIndex: 1,
  },
  editDialogTitle: {
    fontSize: normalize(20),
    fontWeight: 'bold',
    color: '#111827',
    textAlign: 'center',
    marginBottom: normalize(4),
  },
  editDialogSubtitle: {
    fontSize: normalize(12),
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: normalize(24),
  },
  inputGroup: {
    marginBottom: normalize(16),
  },
  inputLabel: {
    fontSize: normalize(13),
    fontWeight: '700',
    color: '#4B5563',
    marginBottom: normalize(8),
  },
  textInput: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: normalize(12),
    paddingHorizontal: normalize(16),
    height: normalize(44),
    fontSize: normalize(14),
    color: '#111827',
  },
  visibilityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: normalize(12),
  },
  visibilityDescription: {
    flex: 1,
    fontSize: normalize(12),
    color: '#6B7280',
  },
  /** textInput 스타일을 터치 가능한 선택 필드로 쓸 때의 정렬 보정 */
  pickerField: {
    justifyContent: 'center',
  },
  pickerFieldText: {
    fontSize: normalize(14),
    color: '#111827',
  },
  pickerFieldPlaceholder: {
    color: '#9CA3AF',
  },
  textInputDisabled: {
    backgroundColor: '#F3F4F6',
    color: '#9CA3AF',
    borderColor: '#E5E7EB',
  },
  rowInputWrap: {
    flexDirection: 'row',
    gap: normalize(10),
  },
  checkButton: {
    backgroundColor: '#F3F4F6',
    borderRadius: normalize(12),
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: normalize(16),
    height: normalize(44),
  },
  checkButtonText: {
    fontSize: normalize(13),
    fontWeight: 'bold',
    color: '#4B5563',
  },
  twoColumnRow: {
    flexDirection: 'row',
    marginBottom: normalize(16),
  },
  genderSelectTrack: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderRadius: normalize(12),
    height: normalize(44),
    padding: normalize(2),
    width: '100%',
  },
  genderOptionButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: normalize(10),
  },
  genderOptionActive: {
    backgroundColor: '#1344FF',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  genderOptionText: {
    fontSize: normalize(13),
    color: '#9CA3AF',
    fontWeight: '500',
  },
  genderOptionActiveText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  actionNavButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: normalize(12),
    paddingHorizontal: normalize(16),
    height: normalize(44),
  },
  actionNavButtonDisabled: {
    backgroundColor: '#F3F4F6',
    borderColor: '#E5E7EB',
    opacity: 0.6,
  },
  actionNavButtonText: {
    fontSize: normalize(13),
    color: '#4B5563',
    fontWeight: '500',
  },
  saveButton: {
    backgroundColor: '#1344FF',
    borderRadius: normalize(14),
    height: normalize(48),
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#1344FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    width: '100%',
  },
  saveButtonText: {
    fontSize: normalize(15),
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  resignLinkButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: normalize(10),
    marginTop: normalize(10),
    marginBottom: normalize(16),
  },
  resignLinkText: {
    fontSize: normalize(13),
    color: '#EF4444',
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fadeOverlay: {
    width: '100%',
    height: normalize(45),
  },
  fadeOverlayContainer: {
    position: 'absolute',
    bottom: normalize(80),
    left: 0,
    right: 0,
    height: normalize(45),
    zIndex: 2,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  scrollHintContainer: {
    position: 'absolute',
    bottom: normalize(2),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: normalize(4),
    backgroundColor: 'rgba(19, 68, 255, 0.08)',
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(3),
    borderRadius: normalize(10),
  },
  scrollHintText: {
    fontSize: normalize(10),
    fontWeight: 'bold',
    color: '#1344FF',
  },
  keyboardAvoidingWrapper: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fixedBottomArea: {
    paddingHorizontal: normalize(24),
    paddingBottom: normalize(20),
    paddingTop: normalize(12),
    backgroundColor: '#FFFFFF',
    zIndex: 3,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    width: '100%',
  },

  /* ── Itinerary Details Area ── */
  itineraryDetailCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: normalize(16),
    padding: normalize(20),
    marginHorizontal: normalize(16),
    marginTop: normalize(16),
    borderWidth: 1,
    borderColor: '#EAECEF',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
  },
  itineraryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(16),
  },
  itineraryTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  itineraryTitle: {
    fontSize: normalize(16),
    fontWeight: 'bold',
    color: '#111827',
  },
  itineraryManageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: normalize(8),
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(5),
    backgroundColor: '#FFFFFF',
  },
  itineraryManageText: {
    fontSize: normalize(11),
    color: '#4B5563',
    fontWeight: 'bold',
  },
  dashedPlanBox: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderStyle: 'dashed',
    borderRadius: normalize(12),
    paddingVertical: normalize(32),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: normalize(16),
  },
  noPlanText: {
    fontSize: normalize(12),
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: normalize(10),
  },
  createPlanLink: {
    fontSize: normalize(13),
    fontWeight: 'bold',
    color: '#1344FF',
  },
  pastRecordBox: {
    backgroundColor: '#F9FAFB',
    borderRadius: normalize(12),
    padding: normalize(16),
    marginTop: normalize(16),
  },
  pastRecordTitle: {
    fontSize: normalize(13),
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: normalize(16),
  },
  noPastRecordText: {
    fontSize: normalize(12),
    color: '#9CA3AF',
    textAlign: 'center',
    paddingVertical: normalize(16),
  },

  /* ── Itinerary Card Items ── */
  itineraryCardWrapper: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: normalize(16),
    width: '100%',
    padding: normalize(16),
    marginBottom: normalize(12),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(8),
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  ddayBadge: {
    backgroundColor: '#1344FF',
    paddingHorizontal: normalize(6),
    paddingVertical: normalize(2),
    borderRadius: normalize(4),
  },
  ddayText: {
    fontSize: normalize(10),
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  statusText: {
    fontSize: normalize(11),
    color: '#6B7280',
    fontWeight: '500',
  },
  cardTitleText: {
    fontSize: normalize(18),
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: normalize(4),
  },
  dateInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(16),
  },
  datePeriodText: {
    fontSize: normalize(12),
    color: '#6B7280',
  },
  checklistContainer: {
    backgroundColor: '#F9FAFB',
    borderRadius: normalize(12),
    padding: normalize(12),
  },
  checklistHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(8),
  },
  checklistTitle: {
    fontSize: normalize(10),
    fontWeight: '700',
    color: '#6B7280',
    letterSpacing: 0.5,
  },
  checklistProgressText: {
    fontSize: normalize(10),
    color: '#4B5563',
    fontWeight: '600',
  },
  taskItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: normalize(6),
  },
  taskText: {
    fontSize: normalize(13),
    color: '#374151',
    flex: 1,
  },
  taskTextCompleted: {
    color: '#9CA3AF',
    textDecorationLine: 'line-through',
  },
  addTaskButton: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    borderRadius: normalize(8),
    paddingVertical: normalize(8),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: normalize(8),
    backgroundColor: '#FFFFFF',
  },
  addTaskButtonText: {
    fontSize: normalize(12),
    color: '#6B7280',
    fontWeight: '500',
  },
  sectionSubtitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(12),
    gap: normalize(4),
  },
  sectionSubtitleText: {
    fontSize: normalize(13),
    fontWeight: 'bold',
    color: '#4B5563',
  },

  /* ── Past Plan Compact List Styles ── */
  pastPlansContainer: {
    gap: normalize(10),
  },
  pastPlanItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: normalize(12),
    padding: normalize(14),
    width: '100%',
  },
  pastPlanLeft: {
    flex: 1,
  },
  pastPlanTitleText: {
    fontSize: normalize(15),
    fontWeight: 'bold',
    color: '#374151',
    marginBottom: normalize(4),
  },
  pastPlanDateText: {
    fontSize: normalize(12),
    color: '#9CA3AF',
  },
  pastPlanBadge: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(4),
    borderRadius: normalize(6),
  },
  pastPlanBadgeText: {
    fontSize: normalize(10),
    color: '#6B7280',
    fontWeight: 'bold',
  },
  sharedBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: '#F97316',
    borderTopRightRadius: normalize(15),
    borderBottomLeftRadius: normalize(16),
    paddingHorizontal: normalize(12),
    paddingVertical: normalize(6),
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 2,
  },
  sharedBadgeText: {
    fontSize: normalize(10),
    fontWeight: 'bold',
    color: '#FFFFFF',
  },

  /* ── Batch Edit Mode Header & Items ── */
  editModeHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  editActionSelectAll: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
    borderRadius: normalize(8),
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
  },
  selectAllCheckSquare: {
    width: normalize(12),
    height: normalize(12),
    borderWidth: 1,
    borderColor: '#9CA3AF',
    borderRadius: normalize(3),
    marginRight: normalize(4),
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectAllCheckSquareChecked: {
    backgroundColor: '#4B5563',
    borderColor: '#4B5563',
  },
  editActionSelectAllText: {
    fontSize: normalize(11),
    color: '#4B5563',
    fontWeight: 'bold',
  },
  editActionDeleteSelected: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FEE2E2',
    backgroundColor: '#FEF2F2',
    borderRadius: normalize(8),
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
  },
  editActionDeleteSelectedText: {
    fontSize: normalize(11),
    color: '#EF4444',
    fontWeight: 'bold',
  },
  editActionCancel: {
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
  },
  editActionCancelText: {
    fontSize: normalize(11),
    color: '#6B7280',
    fontWeight: 'bold',
  },
  cardCheckboxWrap: {
    marginRight: normalize(6),
  },
  cardCheckboxSquare: {
    width: normalize(16),
    height: normalize(16),
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: normalize(4),
    alignItems: 'center',
    justifyContent: 'center',    backgroundColor: '#FFFFFF',
  },
  editSubToolbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    paddingHorizontal: normalize(12),
    paddingVertical: normalize(8),
    borderRadius: normalize(12),
    marginBottom: normalize(16),
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: normalize(16),
    height: normalize(52),
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  backButton: {
    padding: normalize(4),
  },
  headerTitle: {
    fontSize: normalize(18),
    fontFamily: FONTS.bold,
    fontWeight: 'bold',
    color: '#111827',
  },
});
