import { StyleSheet, Dimensions } from 'react-native';
import { normalize } from '../../../utils/normalize';
import { tokens } from '../../../theme/tokens';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const COLORS = {
  primary: tokens.colors.primary,
  primaryTint: tokens.colors.primaryTint,
  sub: tokens.colors.sub,
  background: tokens.colors.background,
  card: tokens.colors.white,
  text: tokens.colors.text,
  textSecondary: tokens.colors.textSecondary,
  placeholder: tokens.colors.textTertiary,
  border: tokens.colors.border,
  borderLight: tokens.colors.borderLight,
  white: tokens.colors.white,
  error: tokens.tones.danger.fg,
  surface: tokens.colors.surface,
};

export const FONTS = tokens.fontFamily;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.surface,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
  },
  loadErrorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    paddingHorizontal: normalize(32),
  },
  loadErrorText: {
    fontFamily: FONTS.medium,
    fontSize: normalize(15),
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: normalize(16),
  },
  loadErrorButton: {
    backgroundColor: COLORS.borderLight,
    borderRadius: normalize(12),
    paddingHorizontal: normalize(24),
    height: normalize(44),
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadErrorButtonText: {
    fontFamily: FONTS.semibold,
    fontSize: normalize(14),
    color: COLORS.textSecondary,
  },
  scrollContainer: {
    paddingBottom: normalize(40),
    backgroundColor: COLORS.white,
  },

  avatarImage: {
    width: normalize(76),
    height: normalize(76),
    borderRadius: normalize(38),
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  levelBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(2),
    borderRadius: normalize(12),
    gap: normalize(3),
  },
  levelBadgeText: {
    fontSize: normalize(10),
    color: COLORS.white,
    fontWeight: 'bold',
  },
  experienceSection: {
    marginBottom: normalize(16),
  },
  experienceLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(6),
  },
  experienceTitle: {
    fontSize: normalize(12),
    color: COLORS.primary,
    fontWeight: 'bold',
  },
  experienceValue: {
    fontSize: normalize(11),
    color: COLORS.placeholder,
  },
  progressBarTrack: {
    height: normalize(6),
    backgroundColor: COLORS.border,
    borderRadius: normalize(3),
    width: '100%',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: COLORS.primary,
    borderRadius: normalize(3),
  },
  statBlock: {
    alignItems: 'center',
  },
  statLabel: {
    fontSize: normalize(11),
    color: COLORS.textSecondary,
  },

  achievementCard: {
    backgroundColor: COLORS.surface,
    borderRadius: normalize(16),
    padding: normalize(20),
    marginHorizontal: normalize(16),
    marginTop: normalize(16),
    borderWidth: 1,
    borderColor: COLORS.placeholder,
    borderStyle: 'dashed',
  },
  achievementHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(16),
  },
  achievementTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  achievementTitle: {
    fontSize: normalize(16),
    fontWeight: 'bold',
    color: COLORS.text,
  },
  achievementProgressBadge: {
    backgroundColor: COLORS.primaryTint,
    paddingHorizontal: normalize(8),
    paddingVertical: normalize(2),
    borderRadius: normalize(12),
  },
  achievementProgressText: {
    fontSize: normalize(10),
    color: COLORS.primary,
    fontWeight: 'bold',
  },
  badgeList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: normalize(8),
  },
  achievementBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
    borderRadius: normalize(8),
    gap: normalize(4),
  },
  badgeText: {
    fontSize: normalize(11),
    fontWeight: 'bold',
  },

  editDialogCard: {
    backgroundColor: COLORS.white,
    borderRadius: normalize(24),
    width: SCREEN_WIDTH * 0.9,
    height: normalize(500),
    overflow: 'hidden',
    alignSelf: 'center',
    ...tokens.shadows.md,
  },
  editDialogHeader: {
    height: normalize(110),
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    position: 'relative',
    paddingTop: normalize(16),
    width: '100%',
    zIndex: 10,
    elevation: 5,
  },
  closeModalButton: {
    position: 'absolute',
    top: normalize(16),
    right: normalize(16),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    width: normalize(28),
    height: normalize(28),
    borderRadius: normalize(14),
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarEditContainer: {
    position: 'absolute',
    bottom: normalize(-40),
    alignSelf: 'center',
    zIndex: 11,
  },
  avatarEditImage: {
    width: normalize(90),
    height: normalize(90),
    borderRadius: normalize(45),
    borderWidth: 4,
    borderColor: COLORS.white,
  },
  avatarEditPlaceholder: {
    width: normalize(90),
    height: normalize(90),
    borderRadius: normalize(45),
    borderWidth: 4,
    borderColor: COLORS.white,
    backgroundColor: COLORS.borderLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: COLORS.primary,
    width: normalize(26),
    height: normalize(26),
    borderRadius: normalize(13),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.white,
  },
  editDialogBody: {
    paddingHorizontal: normalize(24),
    paddingTop: normalize(52),
    paddingBottom: normalize(60),
    zIndex: 1,
  },
  scrollArea: {
    flex: 1,
    zIndex: 1,
  },
  editDialogTitle: {
    fontSize: normalize(20),
    fontWeight: 'bold',
    color: COLORS.text,
    textAlign: 'center',
    marginBottom: normalize(4),
  },
  editDialogSubtitle: {
    fontSize: normalize(12),
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: normalize(24),
  },
  inputGroup: {
    marginBottom: normalize(16),
  },
  inputLabel: {
    fontSize: normalize(13),
    fontWeight: '700',
    color: COLORS.textSecondary,
    marginBottom: normalize(8),
  },
  textInput: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: normalize(12),
    paddingHorizontal: normalize(16),
    height: normalize(44),
    fontSize: normalize(14),
    color: COLORS.text,
  },
  visibilityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: normalize(12),
  },
  visibilityDescription: {
    flex: 1,
    fontSize: normalize(12),
    color: COLORS.textSecondary,
  },

  pickerField: {
    justifyContent: 'center',
  },
  pickerFieldText: {
    fontSize: normalize(14),
    color: COLORS.text,
  },
  pickerFieldPlaceholder: {
    color: COLORS.placeholder,
  },
  textInputDisabled: {
    backgroundColor: COLORS.borderLight,
    color: COLORS.placeholder,
    borderColor: COLORS.border,
  },
  rowInputWrap: {
    flexDirection: 'row',
    gap: normalize(10),
  },
  checkButton: {
    backgroundColor: COLORS.borderLight,
    borderRadius: normalize(12),
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: normalize(16),
    height: normalize(44),
  },
  checkButtonText: {
    fontSize: normalize(13),
    fontWeight: 'bold',
    color: COLORS.textSecondary,
  },
  twoColumnRow: {
    flexDirection: 'row',
    marginBottom: normalize(16),
  },
  genderSelectTrack: {
    flexDirection: 'row',
    backgroundColor: COLORS.borderLight,
    borderRadius: normalize(12),
    height: normalize(44),
    padding: normalize(2),
    width: '100%',
  },
  genderOptionButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: normalize(10),
  },
  genderOptionActive: {
    backgroundColor: COLORS.primary,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  genderOptionText: {
    fontSize: normalize(13),
    color: COLORS.placeholder,
    fontWeight: '500',
  },
  genderOptionActiveText: {
    color: COLORS.white,
    fontWeight: 'bold',
  },
  actionNavButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: normalize(12),
    paddingHorizontal: normalize(16),
    height: normalize(44),
  },
  actionNavButtonDisabled: {
    backgroundColor: COLORS.borderLight,
    borderColor: COLORS.border,
    opacity: 0.6,
  },
  actionNavButtonText: {
    fontSize: normalize(13),
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  saveButton: {
    backgroundColor: COLORS.primary,
    borderRadius: normalize(14),
    height: normalize(48),
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  saveButtonText: {
    fontSize: normalize(15),
    fontWeight: 'bold',
    color: COLORS.white,
  },
  resignLinkButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: normalize(10),
    marginTop: normalize(10),
    marginBottom: normalize(16),
  },
  resignLinkText: {
    fontSize: normalize(13),
    color: COLORS.error,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fadeOverlay: {
    width: '100%',
    height: normalize(45),
  },
  fadeOverlayContainer: {
    position: 'absolute',
    bottom: normalize(80),
    left: 0,
    right: 0,
    height: normalize(45),
    zIndex: 2,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  scrollHintContainer: {
    position: 'absolute',
    bottom: normalize(2),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: normalize(4),
    backgroundColor: 'rgba(19, 68, 255, 0.08)',
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(3),
    borderRadius: normalize(10),
  },
  scrollHintText: {
    fontSize: normalize(10),
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  keyboardAvoidingWrapper: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fixedBottomArea: {
    paddingHorizontal: normalize(24),
    paddingBottom: normalize(20),
    paddingTop: normalize(12),
    backgroundColor: COLORS.white,
    zIndex: 3,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
    width: '100%',
  },

  noPlanText: {
    fontSize: normalize(12),
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: normalize(10),
  },
  createPlanLink: {
    fontSize: normalize(13),
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  noPastRecordText: {
    fontSize: normalize(12),
    color: COLORS.placeholder,
    textAlign: 'center',
    paddingVertical: normalize(16),
  },

  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
  },
  addTaskButton: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderStyle: 'dashed',
    borderRadius: normalize(8),
    paddingVertical: normalize(8),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: normalize(8),
    backgroundColor: COLORS.white,
  },
  addTaskButtonText: {
    fontSize: normalize(12),
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  sectionSubtitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(12),
    gap: normalize(4),
  },
  sectionSubtitleText: {
    fontSize: normalize(13),
    fontWeight: 'bold',
    color: COLORS.textSecondary,
  },

  editModeHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  editActionSelectAll: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    borderRadius: normalize(8),
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
  },
  selectAllCheckSquare: {
    width: normalize(12),
    height: normalize(12),
    borderWidth: 1,
    borderColor: COLORS.placeholder,
    borderRadius: normalize(3),
    marginRight: normalize(4),
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectAllCheckSquareChecked: {
    backgroundColor: COLORS.textSecondary,
    borderColor: COLORS.textSecondary,
  },
  editActionSelectAllText: {
    fontSize: normalize(11),
    color: COLORS.textSecondary,
    fontWeight: 'bold',
  },
  editActionDeleteSelected: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FEE2E2',
    backgroundColor: '#FEF2F2',
    borderRadius: normalize(8),
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
  },
  editActionDeleteSelectedText: {
    fontSize: normalize(11),
    color: COLORS.error,
    fontWeight: 'bold',
  },
  editActionCancel: {
    paddingHorizontal: normalize(10),
    paddingVertical: normalize(6),
  },
  editActionCancelText: {
    fontSize: normalize(11),
    color: COLORS.textSecondary,
    fontWeight: 'bold',
  },
  cardCheckboxWrap: {
    marginRight: normalize(6),
  },
  cardCheckboxSquare: {
    width: normalize(16),
    height: normalize(16),
    borderWidth: 1,
    borderColor: COLORS.placeholder,
    borderRadius: normalize(4),
    alignItems: 'center',
    justifyContent: 'center',    backgroundColor: COLORS.white,
  },
  editSubToolbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    paddingHorizontal: normalize(12),
    paddingVertical: normalize(8),
    borderRadius: normalize(12),
    marginBottom: normalize(16),
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: normalize(16),
    height: normalize(52),
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  backButton: {
    padding: normalize(4),
  },
  headerTitle: {
    fontSize: normalize(18),
    fontFamily: FONTS.bold,
    fontWeight: 'bold',
    color: COLORS.text,
  },

  // 탭은 상자가 아니라 밑줄이 맡는다. 피드·커뮤니티와 같은 규칙이다.
  sectionTabsWrap: {
    backgroundColor: COLORS.white,
  },
  editButton: {
    paddingVertical: normalize(2),
  },
  // 탭 하나가 가로 12를 이미 쓰므로 4만 더해 본문과 같은 16에 맞춘다.
  tabsInset: {
    paddingHorizontal: normalize(4),
    borderBottomColor: COLORS.borderLight,
  },
  tripTabs: {
    marginTop: normalize(11),
    paddingHorizontal: normalize(4),
    borderBottomColor: COLORS.borderLight,
  },

  headerSpacer: {
    width: 28,
  },
  achievementCardDisabled: {
    opacity: 0.6,
  },
  disabledOpacity: {
    opacity: 0.5,
  },
  iconSpacingSmall: {
    marginRight: 4,
  },
  flex1: {
    flex: 1,
  },
  flex1MarginRight12: {
    flex: 1,
    marginRight: 12,
  },

  // ── 마이페이지 재설계: S2 틀 ──
  // 카드와 그림자를 걷어내고 흰 바탕 위에 1px 선과 8px 띠로만 나눈다.
  profileHeader: {
    backgroundColor: COLORS.white,
    paddingHorizontal: normalize(16),
    paddingTop: normalize(18),
    paddingBottom: normalize(15),
  },
  profileTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(14),
  },
  profileAvatar: {
    width: normalize(56),
    height: normalize(56),
    borderRadius: normalize(28),
    backgroundColor: COLORS.borderLight,
  },
  profileAvatarFallback: {
    width: normalize(56),
    height: normalize(56),
    borderRadius: normalize(28),
    backgroundColor: COLORS.borderLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileNameBlock: {
    flex: 1,
    minWidth: 0,
  },
  profileName: {
    fontSize: normalize(21),
    fontFamily: FONTS.bold,
    color: COLORS.text,
    letterSpacing: -0.6,
  },
  profileMeta: {
    fontSize: normalize(11.5),
    color: COLORS.placeholder,
    marginTop: normalize(3),
  },
  profileEditText: {
    fontSize: normalize(12.5),
    fontFamily: FONTS.bold,
    color: COLORS.primary,
  },
  profileVisibility: {
    marginTop: normalize(11),
    fontSize: normalize(11.5),
    color: COLORS.placeholder,
  },
  profileVisibilityStrong: {
    color: COLORS.text,
    fontFamily: FONTS.bold,
  },
  profileStatRow: {
    flexDirection: 'row',
    marginTop: normalize(13),
    gap: normalize(22),
  },
  profileStat: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  profileStatNumber: {
    fontSize: normalize(17),
    fontFamily: FONTS.bold,
    color: COLORS.text,
    marginRight: normalize(5),
    letterSpacing: -0.3,
  },
  profileStatLabel: {
    fontSize: normalize(11.5),
    color: COLORS.placeholder,
  },
  tasteRow: {
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
    paddingHorizontal: normalize(16),
    paddingVertical: normalize(12),
    backgroundColor: COLORS.white,
  },
  tasteHeading: {
    fontSize: normalize(11),
    fontFamily: FONTS.bold,
    color: COLORS.placeholder,
    marginBottom: normalize(5),
  },
  tasteText: {
    fontSize: normalize(12),
    color: COLORS.text,
    lineHeight: normalize(20),
  },
  tasteLabel: {
    fontSize: normalize(11),
    fontFamily: FONTS.bold,
    color: COLORS.placeholder,
  },
  tasteDivider: {
    color: COLORS.border,
  },
  sectionBand: {
    height: normalize(8),
    backgroundColor: COLORS.surface,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: COLORS.borderLight,
  },
  sectionBlock: {
    backgroundColor: COLORS.white,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: normalize(12),
    paddingHorizontal: normalize(16),
    paddingTop: normalize(17),
  },
  sectionHeaderTitle: {
    fontSize: normalize(16.5),
    fontFamily: FONTS.bold,
    color: COLORS.text,
    letterSpacing: -0.4,
  },
  sectionHeaderAction: {
    fontSize: normalize(12.5),
    fontFamily: FONTS.bold,
    color: COLORS.primary,
  },

  // ── 마이페이지 재설계: 일정 행(R3) ──
  planRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: normalize(14),
    paddingHorizontal: normalize(16),
    paddingVertical: normalize(14),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  planRowSelected: {
    backgroundColor: COLORS.borderLight,
  },
  planRail: {
    width: normalize(46),
    alignItems: 'center',
    paddingTop: normalize(1),
  },
  planRailValue: {
    fontSize: normalize(17),
    fontFamily: FONTS.bold,
    color: COLORS.primary,
    letterSpacing: -0.4,
  },
  planRailValuePast: {
    color: COLORS.placeholder,
  },
  planRailCaption: {
    fontSize: normalize(10),
    color: COLORS.placeholder,
    marginTop: normalize(1),
  },
  planBody: {
    flex: 1,
    minWidth: 0,
    borderLeftWidth: 1,
    borderLeftColor: COLORS.borderLight,
    paddingLeft: normalize(14),
  },
  planTitle: {
    fontSize: normalize(16),
    fontFamily: FONTS.bold,
    color: COLORS.text,
    letterSpacing: -0.3,
  },
  planMeta: {
    fontSize: normalize(11.5),
    color: COLORS.placeholder,
    marginTop: normalize(4),
  },
  planMetaStrong: {
    color: COLORS.textSecondary,
    fontFamily: FONTS.bold,
  },
  // 준비물은 막대 하나로만 말한다(C1). 항목을 펼치면 일정보다 준비물이 커진다.
  planChecklist: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
    marginTop: normalize(7),
    paddingVertical: normalize(4),
  },
  planChecklistLabel: {
    fontSize: normalize(10.5),
    color: COLORS.placeholder,
  },
  planChecklistTrack: {
    flex: 1,
    height: normalize(3),
    borderRadius: normalize(2),
    backgroundColor: COLORS.borderLight,
    overflow: 'hidden',
  },
  planChecklistFill: {
    height: '100%',
    backgroundColor: COLORS.primary,
  },
  // 파랑은 이 화면에서 '누를 수 있다'는 뜻이다. 편집·일정 관리와 같은 신호다.
  planChecklistCount: {
    fontSize: normalize(11),
    fontFamily: FONTS.bold,
    color: COLORS.primary,
  },
  planRowMenu: {
    paddingTop: normalize(2),
    paddingLeft: normalize(2),
  },
  planEmpty: {
    paddingHorizontal: normalize(16),
    paddingVertical: normalize(30),
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
});
