import { StyleSheet, Dimensions, PixelRatio } from 'react-native';

export const { width } = Dimensions.get('window');
export const normalize = (size: number) =>
  Math.round(PixelRatio.roundToNearestPixel(size * (width / 360)));

export const COLORS = {
  primary: '#1344FF',
  primaryDark: '#0F36D6',
  lightGray: '#F3F4F6',
  gray: '#E5E7EB',
  darkGray: '#9CA3AF',
  text: '#111827',
  textSecondary: '#6B7280',
  white: '#FFFFFF',
  success: '#34C759',
  error: '#FF3B30',
  surface: '#F9FAFB',
  border: '#E5E7EB',
};

export const FONTS = {
  regular: 'Pretendard Variable',
  medium: 'Pretendard Variable',
  semibold: 'Pretendard Variable',
  bold: 'Pretendard Variable',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  header: {
    position: 'relative',
    paddingHorizontal: normalize(24),
    paddingTop: normalize(36),
    paddingBottom: normalize(10),
  },
  headerBackButton: {
    position: 'absolute',
    top: normalize(36),
    right: normalize(24),
    width: normalize(34),
    height: normalize(34),
    borderRadius: normalize(17),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  stepIndicatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
    marginBottom: normalize(12),
  },
  stepDot: {
    height: normalize(6),
    borderRadius: normalize(3),
    backgroundColor: COLORS.gray,
  },
  stepDotActive: {
    backgroundColor: COLORS.primary,
  },
  stepText: {
    fontSize: normalize(12),
    fontFamily: FONTS.bold,
    fontWeight: '700',
    lineHeight: normalize(16),
    color: COLORS.primary,
    marginBottom: normalize(4),
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  scrollContent: {
    padding: normalize(24),
    paddingBottom: normalize(100),
  },
  title: {
    fontSize: normalize(32),
    fontFamily: FONTS.bold,
    fontWeight: '700',
    lineHeight: normalize(40),
    letterSpacing: 0.2,
    color: COLORS.text,
    marginBottom: normalize(8),
    textAlign: 'left',
  },
  description: {
    fontSize: normalize(15),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(24),
    letterSpacing: 0.1,
    color: COLORS.textSecondary,
    marginBottom: normalize(32),
    textAlign: 'left',
  },
  inputGroup: {
    width: '100%',
    marginBottom: normalize(14),
  },
  inputContainer: {
    width: '100%',
    minHeight: normalize(68),
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    paddingHorizontal: normalize(16),
    paddingVertical: normalize(10),
    backgroundColor: COLORS.white,
    justifyContent: 'center',
  },
  label: {
    fontSize: normalize(11),
    color: COLORS.textSecondary,
    marginBottom: normalize(2),
    fontFamily: FONTS.medium,
    fontWeight: '500',
    lineHeight: normalize(16),
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  flex1: { flex: 1 },
  input: {
    flex: 1,
    fontSize: normalize(16),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(20),
    padding: 0,
    color: COLORS.text,
    height: normalize(28),
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  emailValueWrapper: {
    flex: 1,
    justifyContent: 'center',
  },
  emailValue: {
    fontSize: normalize(16),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(28),
    color: COLORS.text,
    padding: 0,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  inputFocused: {
    borderColor: COLORS.primary,
    borderWidth: 2,
  },
  inputDisabled: {
    backgroundColor: COLORS.lightGray,
    color: COLORS.darkGray,
  },
  resendButton: {
    alignSelf: 'flex-end',
    marginTop: normalize(10),
    paddingVertical: normalize(4),
    paddingHorizontal: normalize(2),
  },
  resendButtonDisabled: {
    opacity: 0.5,
  },
  resendButtonText: {
    fontSize: normalize(13),
    fontFamily: FONTS.medium,
    fontWeight: '500',
    lineHeight: normalize(18),
    color: COLORS.primary,
    textDecorationLine: 'underline',
  },
  codeInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  innerInput: {
    flex: 1,
    fontSize: normalize(16),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(20),
    color: COLORS.text,
    height: normalize(28),
    padding: 0,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  timerText: {
    color: COLORS.error,
    fontFamily: FONTS.bold,
    fontWeight: '700',
    fontSize: normalize(14),
    lineHeight: normalize(18),
  },

  tempPasswordContainer: {
    marginTop: normalize(20),
    alignItems: 'center',
  },
  infoBox: {
    backgroundColor: COLORS.surface,
    padding: normalize(20),
    borderRadius: 12,
    width: '100%',
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
  },
  infoBoxText: {
    fontSize: normalize(16),
    fontFamily: FONTS.bold,
    fontWeight: '700',
    lineHeight: normalize(22),
    color: COLORS.text,
  },
  infoBoxSubText: {
    fontSize: normalize(14),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(20),
    color: COLORS.textSecondary,
    textAlign: 'center',
  },

  footer: {
    padding: normalize(24),
    backgroundColor: COLORS.white,
    justifyContent: 'flex-end',
  },
  submitButton: {
    width: '100%',
    height: normalize(52),
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
  },
  submitButtonDisabled: {
    backgroundColor: COLORS.darkGray,
  },
  submitButtonText: {
    fontSize: normalize(17),
    fontFamily: FONTS.bold,
    fontWeight: '700',
    color: COLORS.white,
    letterSpacing: 0.2,
    lineHeight: normalize(22),
  },
  retryButton: {
    alignItems: 'center',
    paddingVertical: normalize(12),
    marginTop: normalize(8),
  },
  retryButtonText: {
    fontSize: normalize(14),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(18),
    color: COLORS.textSecondary,
    textDecorationLine: 'underline',
  },
  backButton: {
    alignItems: 'center',
    paddingVertical: normalize(12),
    marginTop: normalize(12),
  },
  backButtonText: {
    fontSize: normalize(14),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(18),
    color: COLORS.textSecondary,
    textDecorationLine: 'underline',
  },
});
