import { StyleSheet, Dimensions, PixelRatio } from 'react-native';

export const { width } = Dimensions.get('window');
export const normalize = (size: number) =>
  Math.round(PixelRatio.roundToNearestPixel(size * (width / 360)));

export const COLORS = {
  primary: '#1344FF',
  primaryDark: '#0F36D6',
  gray: '#E5E7EB',
  darkGray: '#9CA3AF',
  text: '#111827',
  textSecondary: '#6B7280',
  white: '#FFFFFF',
  error: '#FF3B30',
  surface: '#F9FAFB',
  border: '#E5E7EB',
};

export const FONTS = {
  regular: 'Pretendard Variable',
  medium: 'Pretendard Variable',
  semibold: 'Pretendard Variable',
  bold: 'Pretendard Variable',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: normalize(24),
    backgroundColor: COLORS.white,
  },
  title: {
    fontSize: normalize(32),
    fontFamily: FONTS.bold,
    fontWeight: '700',
    lineHeight: normalize(40),
    letterSpacing: 0.2,
    textAlign: 'center',
    marginBottom: normalize(32),
    color: COLORS.text,
  },
  inputGroup: {
    width: '100%',
    marginBottom: normalize(14),
  },
  inputContainer: {
    width: '100%',
    height: normalize(60),
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    paddingHorizontal: normalize(16),
    paddingVertical: normalize(8),
    backgroundColor: COLORS.white,
    justifyContent: 'center',
  },
  label: {
    fontSize: normalize(11),
    color: COLORS.textSecondary,
    marginBottom: normalize(2),
    fontFamily: FONTS.medium,
    fontWeight: '500',
    lineHeight: normalize(16),
  },
  input: {
    width: '100%',
    fontSize: normalize(16),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(20),
    color: COLORS.text,
    padding: 0,
    includeFontPadding: false,
    height: normalize(24),
  },
  passwordContainer: {
    width: '100%',
    height: normalize(60),
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    paddingHorizontal: normalize(16),
    paddingVertical: normalize(8),
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
  },
  passwordContent: {
    flex: 1,
    justifyContent: 'center',
  },
  passwordInput: {
    width: '100%',
    fontSize: normalize(16),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(20),
    color: COLORS.text,
    padding: 0,
    includeFontPadding: false,
    height: normalize(24),
  },
  passwordToggleText: {
    color: COLORS.textSecondary,
    fontSize: normalize(14),
    fontFamily: FONTS.semibold,
    fontWeight: '600',
    lineHeight: normalize(20),
  },
  inputFocused: {
    borderColor: COLORS.primary,
    borderWidth: 2.5,
  },
  submitButton: {
    width: '100%',
    height: normalize(52),
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    marginTop: normalize(24),
  },
  submitButtonDisabled: {
    backgroundColor: COLORS.darkGray,
  },
  submitButtonText: {
    fontSize: normalize(17),
    fontFamily: FONTS.bold,
    fontWeight: '700',
    lineHeight: normalize(22),
    color: COLORS.white,
    letterSpacing: 0.2,
  },
  linksContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginTop: normalize(28),
    gap: normalize(24),
  },
  separatorWrapper: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  separator: {
    color: COLORS.darkGray,
    fontSize: normalize(14),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(18),
  },
  linkButton: {
    paddingVertical: normalize(6),
    paddingHorizontal: normalize(12),
    borderRadius: 8,
  },
  linkText: {
    color: COLORS.darkGray,
    fontSize: normalize(14),
    fontFamily: FONTS.medium,
    fontWeight: '500',
    lineHeight: normalize(18),
  },

  /* ── Social Login ── */
  socialContainer: {
    width: '100%',
    marginTop: normalize(20),
    marginBottom: normalize(12),
    alignItems: 'center',
  },
  socialDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: normalize(14),
  },
  socialDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: COLORS.border,
  },
  socialDividerText: {
    marginHorizontal: normalize(12),
    fontSize: normalize(12),
    fontFamily: FONTS.medium,
    fontWeight: '500',
    lineHeight: normalize(16),
    color: COLORS.darkGray,
  },
  socialButtons: {
    flexDirection: 'row',
    gap: normalize(20),
  },
  socialButton: {
    width: normalize(48),
    height: normalize(48),
    borderRadius: normalize(24),
    borderWidth: 1,
    borderColor: COLORS.border,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },

  /* ── Privacy Policy Link ── */
  privacyLinkText: {
    fontSize: normalize(12),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(16),
    color: COLORS.darkGray,
    textDecorationLine: 'underline',
    textAlign: 'center',
    marginBottom: normalize(4),
  },

  /* ── Privacy Policy Modal ── */
  privacyOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: normalize(16),
  },
  privacyModal: {
    width: '100%',
    maxHeight: '80%',
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: normalize(20),
  },
  privacyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(16),
  },
  privacyTitle: {
    fontSize: normalize(18),
    fontFamily: FONTS.bold,
    fontWeight: '700',
    lineHeight: normalize(24),
    color: COLORS.text,
  },
  privacyScroll: {
    marginBottom: normalize(16),
  },
  privacySectionTitle: {
    fontSize: normalize(13),
    fontFamily: FONTS.bold,
    fontWeight: '700',
    lineHeight: normalize(18),
    color: COLORS.text,
    marginTop: normalize(12),
    marginBottom: normalize(6),
  },
  privacyBullet: {
    fontSize: normalize(12),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    color: COLORS.textSecondary,
    lineHeight: normalize(18),
    marginBottom: normalize(3),
    paddingLeft: normalize(4),
  },
  privacyCloseButton: {
    height: normalize(52),
    width: '100%',
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  privacyCloseButtonText: {
    fontSize: normalize(15),
    fontFamily: FONTS.bold,
    fontWeight: '700',
    lineHeight: normalize(20),
    color: COLORS.white,
  },
});
