import { StyleSheet, Dimensions, PixelRatio } from 'react-native';

export const { width, height } = Dimensions.get('window');
export const normalize = (size: number) =>
  Math.round(PixelRatio.roundToNearestPixel(size * (width / 360)));

export const COLORS = {
  primary: '#1344FF',
  primaryDark: '#0F36D6',
  lightGray: '#F3F4F6',
  gray: '#E5E7EB',
  darkGray: '#9CA3AF',
  text: '#111827',
  textSecondary: '#6B7280',
  white: '#FFFFFF',
  success: '#34C759',
  error: '#FF3B30',
  surface: '#F9FAFB',
  border: '#E5E7EB',
  modalBackground: 'rgba(0, 0, 0, 0.5)',
};

export const FONTS = {
  regular: 'Inter_400Regular',
  medium: 'Inter_500Medium',
  semibold: 'Inter_600SemiBold',
  bold: 'Inter_700Bold',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.white },
  header: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: normalize(20),
    paddingTop: normalize(20),
    paddingBottom: normalize(10),
    marginTop: normalize(10),
  },
  stepIndicator: {
    backgroundColor: COLORS.surface,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  stepText: {
    fontSize: normalize(14),
    fontFamily: FONTS.semibold,
    color: COLORS.primary,
  },
  scrollContainer: { padding: normalize(24), paddingBottom: normalize(100) },
  title: {
    fontSize: normalize(28),
    fontFamily: FONTS.bold,
    color: COLORS.text,
    marginBottom: normalize(8),
  },
  description: {
    fontSize: normalize(15),
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary,
    marginBottom: normalize(32),
  },
  inputGroup: { marginBottom: normalize(24) },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(8),
  },
  label: {
    fontSize: normalize(14),
    color: COLORS.text,
    fontFamily: FONTS.semibold,
    marginLeft: normalize(4),
    marginBottom: normalize(8),
  },
  changeEmailText: {
    fontSize: normalize(12),
    color: COLORS.primary,
    textDecorationLine: 'underline',
    marginRight: normalize(4),
  },
  input: {
    height: normalize(52),
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    paddingHorizontal: normalize(16),
    fontSize: normalize(16),
    fontFamily: FONTS.regular,
    backgroundColor: COLORS.white,
    color: COLORS.text,
  },
  inputFocused: {
    borderColor: COLORS.primary,
    borderWidth: 2,
  },
  inputDisabled: {
    backgroundColor: COLORS.lightGray,
    color: COLORS.darkGray,
  },
  errorText: {
    color: COLORS.error,
    fontSize: normalize(13),
    fontFamily: FONTS.regular,
    marginTop: normalize(8),
    marginLeft: normalize(4),
  },
  inlineInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  flex1: { flex: 1 },
  inlineButton: {
    height: normalize(52),
    paddingHorizontal: normalize(20),
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    minWidth: normalize(80),
  },
  buttonDisabled: { backgroundColor: COLORS.darkGray },
  inlineButtonText: {
    color: COLORS.white,
    fontFamily: FONTS.bold,
    fontSize: normalize(14),
  },
  codeInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  codeInput: {
    flex: 1,
    fontSize: normalize(16),
    fontFamily: FONTS.regular,
    padding: 0,
    color: COLORS.text,
  },
  timerText: {
    color: COLORS.error,
    fontFamily: FONTS.bold,
    fontSize: normalize(14),
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    height: normalize(52),
  },
  passwordInput: {
    flex: 1,
    height: '100%',
    paddingHorizontal: normalize(16),
    fontSize: normalize(16),
    fontFamily: FONTS.regular,
    color: COLORS.text,
  },
  eyeIcon: { padding: normalize(16) },
  requirementsContainer: {
    marginTop: normalize(12),
    marginLeft: normalize(10),
  },
  requirementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(4),
  },
  requirementIcon: {
    marginRight: normalize(8),
    fontFamily: FONTS.bold,
    fontSize: normalize(14),
  },
  requirementText: { fontSize: normalize(13), fontFamily: FONTS.regular },
  genderContainer: { flexDirection: 'row', gap: normalize(12) },
  genderButton: {
    flex: 1,
    height: normalize(52),
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  genderButtonSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  genderButtonText: {
    fontSize: normalize(16),
    fontFamily: FONTS.semibold,
    color: COLORS.textSecondary,
  },
  genderButtonTextSelected: { color: COLORS.white },
  footer: { padding: normalize(24), backgroundColor: COLORS.white },
  submitButton: {
    width: '100%',
    height: normalize(56),
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
  },
  submitButtonText: {
    fontSize: normalize(18),
    fontFamily: FONTS.bold,
    color: COLORS.white,
  },
  retryButton: {
    alignItems: 'center',
    padding: normalize(12),
    marginTop: normalize(8),
  },
  retryButtonText: {
    fontSize: normalize(14),
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary,
    textDecorationLine: 'underline',
  },
  bottomBackButton: {
    alignItems: 'center',
    padding: normalize(12),
    marginTop: normalize(12),
  },
  bottomBackButtonText: {
    fontSize: normalize(14),
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary,
    textDecorationLine: 'underline',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.modalBackground,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    width: width * 0.8,
    maxHeight: height * 0.6,
    borderRadius: 12,
    padding: normalize(20),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  modalTitle: {
    fontSize: normalize(20),
    fontFamily: FONTS.bold,
    marginBottom: normalize(16),
    textAlign: 'center',
    color: COLORS.text,
  },
  ageOption: {
    paddingVertical: normalize(12),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGray,
  },
  ageOptionText: {
    fontSize: normalize(16),
    fontFamily: FONTS.regular,
    textAlign: 'center',
    color: COLORS.text,
  },
  marginBottom0: {
    marginBottom: 0,
  },
  justifyCenter: {
    justifyContent: 'center',
  },
});
