import { StyleSheet, Dimensions, PixelRatio } from 'react-native';

export const { width, height } = Dimensions.get('window');
export const normalize = (size: number) =>
  Math.round(PixelRatio.roundToNearestPixel(size * (width / 360)));

export const COLORS = {
  primary: '#1344FF',
  primaryDark: '#0F36D6',
  lightGray: '#F3F4F6',
  gray: '#E5E7EB',
  darkGray: '#9CA3AF',
  text: '#111827',
  textSecondary: '#6B7280',
  white: '#FFFFFF',
  success: '#34C759',
  error: '#FF3B30',
  surface: '#F9FAFB',
  border: '#E5E7EB',
  modalBackground: 'rgba(0, 0, 0, 0.5)',
};

export const FONTS = {
  regular: 'Pretendard Variable',
  medium: 'Pretendard Variable',
  semibold: 'Pretendard Variable',
  bold: 'Pretendard Variable',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.white },
  header: {
    paddingHorizontal: normalize(24),
    paddingTop: normalize(20),
    paddingBottom: normalize(10),
  },
  stepIndicatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(6),
    marginBottom: normalize(12),
  },
  stepDot: {
    height: normalize(6),
    borderRadius: normalize(3),
    backgroundColor: COLORS.gray,
  },
  stepDotActive: {
    backgroundColor: COLORS.primary,
  },
  stepText: {
    fontSize: normalize(12),
    fontFamily: FONTS.bold,
    fontWeight: '700',
    lineHeight: normalize(16),
    color: COLORS.primary,
    marginBottom: normalize(4),
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  scrollContainer: { padding: normalize(24), paddingBottom: normalize(100) },
  title: {
    fontSize: normalize(32),
    fontFamily: FONTS.bold,
    fontWeight: '700',
    lineHeight: normalize(40),
    letterSpacing: 0.2,
    color: COLORS.text,
    marginBottom: normalize(8),
    textAlign: 'left',
  },
  description: {
    fontSize: normalize(15),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(24),
    letterSpacing: 0.1,
    color: COLORS.textSecondary,
    marginBottom: normalize(32),
    textAlign: 'left',
  },
  inputGroup: { marginBottom: normalize(24) },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: normalize(8),
  },
  label: {
    fontSize: normalize(14),
    color: COLORS.text,
    fontFamily: FONTS.semibold,
    fontWeight: '600',
    lineHeight: normalize(18),
    marginLeft: normalize(4),
    marginBottom: normalize(8),
  },
  changeEmailText: {
    fontSize: normalize(12),
    color: COLORS.primary,
    textDecorationLine: 'underline',
    marginRight: normalize(4),
    fontWeight: '500',
    lineHeight: normalize(16),
  },
  input: {
    height: normalize(52),
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    paddingHorizontal: normalize(16),
    fontSize: normalize(16),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(20),
    backgroundColor: COLORS.white,
    color: COLORS.text,
  },
  inputFocused: {
    borderColor: COLORS.primary,
    borderWidth: 2,
  },
  inputDisabled: {
    backgroundColor: COLORS.lightGray,
    color: COLORS.darkGray,
  },
  errorText: {
    color: COLORS.error,
    fontSize: normalize(13),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(18),
    marginTop: normalize(8),
    marginLeft: normalize(4),
  },
  inlineInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: normalize(8),
  },
  flex1: { flex: 1 },
  inlineButton: {
    height: normalize(52),
    paddingHorizontal: normalize(14),
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    minWidth: normalize(72),
    flexShrink: 0,
  },
  buttonDisabled: { backgroundColor: COLORS.darkGray },
  inlineButtonText: {
    color: COLORS.white,
    fontFamily: FONTS.bold,
    fontWeight: '700',
    fontSize: normalize(14),
    lineHeight: normalize(18),
  },
  codeInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  codeInput: {
    flex: 1,
    fontSize: normalize(16),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(20),
    padding: 0,
    color: COLORS.text,
  },
  timerText: {
    color: COLORS.error,
    fontFamily: FONTS.bold,
    fontWeight: '700',
    fontSize: normalize(14),
    lineHeight: normalize(18),
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    height: normalize(60),
  },
  passwordInput: {
    flex: 1,
    height: '100%',
    paddingHorizontal: normalize(16),
    fontSize: normalize(16),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(20),
    color: COLORS.text,
  },
  eyeIcon: { padding: normalize(16) },
  requirementsContainer: {
    marginTop: normalize(12),
    marginLeft: normalize(10),
  },
  requirementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: normalize(4),
  },
  requirementIcon: {
    marginRight: normalize(8),
    fontFamily: FONTS.bold,
    fontSize: normalize(14),
    fontWeight: '700',
    lineHeight: normalize(18),
  },
  requirementText: {
    fontSize: normalize(13),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(18),
  },
  genderContainer: { flexDirection: 'row', gap: normalize(12) },
  genderButton: {
    flex: 1,
    height: normalize(60),
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  genderButtonSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  genderButtonText: {
    fontSize: normalize(16),
    fontFamily: FONTS.semibold,
    color: COLORS.textSecondary,
    fontWeight: '600',
    lineHeight: normalize(20),
  },
  genderButtonTextSelected: { color: COLORS.white },
  footer: { padding: normalize(24), backgroundColor: COLORS.white },
  submitButton: {
    width: '100%',
    height: normalize(52),
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
  },
  submitButtonText: {
    fontSize: normalize(17),
    fontFamily: FONTS.bold,
    fontWeight: '700',
    lineHeight: normalize(22),
    color: COLORS.white,
    letterSpacing: 0.2,
  },
  retryButton: {
    alignItems: 'center',
    padding: normalize(12),
    marginTop: normalize(8),
  },
  retryButtonText: {
    fontSize: normalize(14),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(18),
    color: COLORS.textSecondary,
    textDecorationLine: 'underline',
  },
  bottomBackButton: {
    alignItems: 'center',
    padding: normalize(12),
    marginTop: normalize(12),
  },
  bottomBackButtonText: {
    fontSize: normalize(14),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(18),
    color: COLORS.textSecondary,
    textDecorationLine: 'underline',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.modalBackground,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    width: width * 0.8,
    maxHeight: height * 0.6,
    borderRadius: 12,
    padding: normalize(20),
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  modalTitle: {
    fontSize: normalize(20),
    fontFamily: FONTS.bold,
    fontWeight: '700',
    lineHeight: normalize(24),
    marginBottom: normalize(16),
    textAlign: 'center',
    color: COLORS.text,
  },
  ageOption: {
    paddingVertical: normalize(12),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGray,
  },
  ageOptionText: {
    fontSize: normalize(16),
    fontFamily: FONTS.regular,
    fontWeight: '400',
    lineHeight: normalize(20),
    textAlign: 'center',
    color: COLORS.text,
  },
  marginBottom0: {
    marginBottom: 0,
  },
  justifyCenter: {
    justifyContent: 'center',
  },
});
